### ISSUE TITLE
How to customise or hide the Scale buttons?

### ISSUE THREAD

**Issue by zxzfcsu** [osmdroid/osmdroid#1039]
## Issue Type

[ ] Question

## Description and/or steps/code to reproduce the problem
How to customise or display the Scale buttons?
![_20180521143457](https://user-images.githubusercontent.com/26213905/40293848-5a1604e4-5d05-11e8-8c25-605299075d47.jpg)

### Version of osmdroid the issue relates to:

6.0.1

**Comment by monsieurtanuki** [comment]
@zxzfcsu You mean the zoom buttons. The short answer is: you cannot customize them as they are (soon-to-be-deprecated) Android standards, and I think you can just set their appearance on/off.

That being said, @spyhunter99 and I already tried to get rid of those standard buttons last year. But we received comments such as "you did not implement all the standard features, for instance the fade out", and we rolled back as it was not the main dev focus (I started only because the standard zoom buttons triggered not-crashing exceptions that polluted the logs).

My answer is therefore a question: what do you guys expect of zoom buttons? I guess it would be something like:
* a custom look for both buttons, with default values
* a custom positioning for both buttons
* a settable fade out
* an "always show" true/false set up

I would be a big fan of permanent simple "+" and "-" white square, like in google maps.
Which could be implemented with the features I just listed.

Do you think of other features?

**Comment by 18633847058** [comment]
mapView.setBuiltInZoomControls(false);

**Comment by zxzfcsu** [comment]
Sorry for replying so late.
Maybe not buttons.Buttons are simple and clean,but not accord with people's insight of aesthetic appreciation.I think something like music waves is much better.

**Comment by spyhunter99** [comment]
looks like this is answered, reopen if there's more questions on this
