### ISSUE TITLE
osmdroid problem downloading MapTiles with Mapnik, HTTP response Moved Permanently

### ISSUE THREAD

**Issue by Westblat** [osmdroid/osmdroid#1048]
## Issue Type

[x] Question
[x] Bug

## Description and/or steps/code to reproduce the problem
I added an osmdroid map on my android app on Friday. This Monday when I tried to run the app I keep getting Error  
`W/OsmDroid: Problem downloading MapTile: /14/9329/4750 HTTP response: Moved Permanently`
I tried to google around, but didn't find a solution for this.
I'm using the MAPNIK maps.

I'm using osmdroid version 6.0.1 and tested it with emulated devices with APK 27 and 22. And two different physical devices. None of them worked

**Comment by Westblat** [comment]
I managed to track down the issue using custom urls for the map. I got the wikimedia maps to work, so I believe the problem is thath the osmdroid is using the wrong url to get the MAPNIK maps. I don't know the current urls where to find these maps right now

**Comment by mlytvyn80** [comment]
Which Wikimedia URL have you used?

**Comment by Westblat** [comment]
The urls gotten from this site

https://wiki.openstreetmap.org/wiki/Tile_servers

**Comment by cbalster** [comment]
Sorry - I didn't see your issue and just opened a duplicate which has a little more background:
https://github.com/osmdroid/osmdroid/issues/1050
Basically the hotfix for your app should be to use your own implementation of the mapnik OnlineTileSourceBase with the urls switched to https.

**Comment by monsieurtanuki** [comment]
@Westblat cf. #1051 I believe that the Mapnik http urls (like [http://a.tile.openstreetmap.org/14/9329/4750.png](http://a.tile.openstreetmap.org/14/9329/4750.png)) do work again now with a 200 response code (not a redirection code). Could you please retry?

**Comment by spyhunter99** [comment]
hmm they might be trying to switch to ssl only, which is fine. We should update the sources and publish an update. @monsieurtanuki what else is left for this release? (i.e. can we cut now?)

**Comment by cbalster** [comment]
It seems for now they reverted to not enforcing https:
https://github.com/openstreetmap/chef/commit/6088534f1b61e4667c74e4b83a82ba434b22e494
Still this is an important issue that should be taken care of since it can break all production apps using osmdroid with mapnik from one day to the other.
I see several options here which I already mentioned in #1050 . Personally I think the best solution would be to switch to okhttp - but it has a minsdk of 10. Another option would be to manually handle all redirect response codes in the downloader code and fire of another request using the redirection URL passed in the response header to the initial request.

**Comment by monsieurtanuki** [comment]
@cbalster I agree: for the moment we can survive with http but it would be nice to handle https as well.
The problem is that https tiles work within apps but don't within the unit tests - as a fortunate side effect we control that we are able to load tiles in test `Bug512CacheManagerWp`.
Regarding okhttp, I don't think that would solve the problem for two good reasons:
* in a previous issue we incidentally discovered that Android now uses internally okhttp anyway (cf. #989)
* it's more a problem like "I need some configuration in order to use https" (like public key exchange), which is tacitly handled by web browser or Android app, but not by our current unit test set up.

@spyhunter99 As you know about the unit test set up, what do you think prevent the https from working?

**Comment by monsieurtanuki** [comment]
@cbalster Oops, I just noticed that you already mentioned the https setup issue in #1051.
A lousy/temporary solution could be to:
* set up the mapnik tile source (`TileSourceFactory.MAPNIK`) with https base urls - which is a good target
* in `Bug512CacheManagerWp` unit test, use a ad-hoc new explicit tile source - like mapnik in http, because in that unit test we only want to check if we successfully download the expected number of tiles regardless of the tile source
* in the meanwhile, try to make unit tests work with https, and create a dedicated unit test that checks if we download "standard" mapnik tiles with `TileSourceFactory.MAPNIK` (https version)

@spyhunter99
> can we cut now?

I have no pending dev

**Comment by cbalster** [comment]
@monsieurtanuki Sounds good to me. :+1:  I will add the 2nd point to my PR. 
Regarding the previous post: Yes, Android started using okhhtp internally, but it's an older version and I don't know if it's HttpUrlConnection implementation offers the same features as the okhttp API regarding auto-following redirects and handling a lot of other http weirdness for you. I will try to take a closer look at that on the weekend.
