### ISSUE TITLE
New center not saved in MapView prior to call to MapListener::onScroll()

### ISSUE THREAD

**Issue by saemy** [osmdroid/osmdroid#1055]
## Issue Type

[x] Bug

## Description and/or steps/code to reproduce the problem

`MapController::setCenter()` fires `MapListener::onScroll()` prior to storing the new center in the MapView. Moreover, the event indicates a scroll with `x` and `y` set to zero. Therefore, in the listener there is no way to tell to which position the map is scrolling to.

In contrast,
  - `MapView::scrollTo()` saves the scroll in the MapView and delivers it in the event
  - `MapView::setZoomLevel()` saves the zoom level and delivers the new zoom level in the event
  - `MapController::zoomToFixing()` does not save the zoom level in the MapView but delivers the new zoom level in the event

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

tip of master

**Comment by monsieurtanuki** [comment]
@saemy You're right. I guess that if in `MapController.setCenter` we move the calls to listeners at the end of the method (after `mMapView.setExpectedCenter(point)`) it will make more sense. Do you agree?

By the way you can retrieve the actual map position from `event.getSource().getProjection().getCurrentCenter()`

**Comment by saemy** [comment]
Yes.

**Comment by monsieurtanuki** [comment]
@saemy Should be solved by #1059. Could you give it a try?

**Comment by monsieurtanuki** [comment]
@saemy ping

**Comment by saemy** [comment]
Sorry, I was no able to test it yet. Is there any nightly build that I can use?

**Comment by monsieurtanuki** [comment]
@saemy I don't know, I'm clueless regarding builds.

**Comment by PattaFeuFeu** [comment]
This hasn’t, by any chance, been fixed in [v6.0.2](https://github.com/osmdroid/osmdroid/releases/tag/osmdroid-parent-6.0.2)?

**Comment by monsieurtanuki** [comment]
As far as I understood the issue it should be fixed by #1059, but it would make sense to have not the developer but someone else check the fix. I don't know if @saemy currently has the time to check it. @PattaFeuFeu Would you check the fix?
PS: I merged #1059 on June 10th and 6.0.2 was released on July 16th.

**Comment by saemy** [comment]
Sorry for the delay. The released code was modified once more in fe24316. But this bug seems fixed.

One related issue is that if one wants to change the center+zoom, one needs to call `setZoom()` and `setCenter()` separately as `MapController::animateTo(final IGeoPoint point, final Double pZoom, final Long pSpeed)` is not present in the interface. And `setZoom()` is first calling `setExpectedCenter()` with `getProjection().getCurrentCenter()` which is issuing the `onScroll()` callback with the new zoom level already set on the map but still the old center of the projection. Then it sets the zoom and calls the `onZoom()` callback. Then we set the center and the `onScroll()` callback is called once more - now with the correct position and zoom on the map.

**Comment by monsieurtanuki** [comment]
@saemy 
> The released code was modified once more

You're right, the calls to `ScrollEvent`s were moved to `MapView.setExpectedCenter`.

> `MapController::animateTo(final IGeoPoint point, final Double pZoom, final Long pSpeed)` is not present in the interface.

I believe it's because the interface was created more than 6 years ago in order to match Google Maps' at the time.
I guess you'd be better off using directly `MapController` instead of `IMapController`, or cast it accordingly.

I'm closing the issue as it looks fixed, but don't hesitate to reopen it if necessary, or to open a new issue regarding the missing `IMapController.animateTo` methods. For the record I even created a month ago a version that includes `Float pOrientation`.
