### ISSUE TITLE
Memory issue with mapview.

### ISSUE THREAD

**Issue by mdakram** [osmdroid/osmdroid#107]
![osmdroid](https://cloud.githubusercontent.com/assets/1751271/7086292/9d37b004-df9c-11e4-9aca-a5091a19bed9.png)

I was running a sample based on osmdroid and my phone became slow. So i tried to dig in and found sample based on this awesome library is taking too much memory for single paged mapview. 

attached is the screenshot. and sample is from https://github.com/MKergall/osmbonuspack.

**Comment by spyhunter99** [comment]
what version of osmdroid are you using? what's the sample? how much stuff is added on the map? what version of osmbonuspack? The slowest is probably the garbage collector.

**Comment by mdakram** [comment]
@spyhunter99 its nothing on map just plain MapView and sample (OSMBonusPackTuto ) is using OSMDROID 4.3.

**Comment by Dekje75** [comment]
@mdakram Did you solve the problem?
I am having the same problem. Huge increase of memory in Osmdroid. To see what is causing the problem i made a test app with only the Osmdroid map. Using the map in the emulator i notice two things:
1. Every time I zoom in, the heap allocating almost doubles. Looks like the complete map is downloaded (cached). I can only see the first three times of zooming because after that the app crashes.
2. The garbage collector does not seem to clean the old tiles. If I do a clean after the map loads there is no decrease in allocated memory.

I used the official example with the .jar file. Is this behavior caused by an implementation error or is it an error in the library?

**Comment by spyhunter99** [comment]
This behavior doesn't seem to be present in master, can you retest your scenario with it?

**Comment by spyhunter99** [comment]
operation timeout. reopen if it's still an issue for you with device specifics, api levels, etc
