### ISSUE TITLE
Update to target api 26 to comply with playstore rules

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#1098]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[ ] Question
[ ] Bug
[ ] Improvement
[ x] Build system related
[ ] Performance
[ ] Documentation

**Comment by cbalster** [comment]
Since this is becoming a problem for the demo app by the end of the month, I was wondering if there is any progress on this?
If I remember correctly the main problem here is gradlefury not working with gradle => 3.4 which prevents updating the support libs/build tools since they at some point require higher versions of gradle. Any chance of making gradlefury work with newer gradle versions?

**Comment by spyhunter99** [comment]
Damn. I'm super busy at the moment. Maybe this weekend I can look at it.
The android gradle changes prevent pom generation for some reason. I can
try to manually generate it with strings, but that's no fun.

**Comment by spyhunter99** [comment]
looking into it now. just did a test build. sonatype fails us on both javadocs and sources jar missing on the jre tile packager.

**Comment by spyhunter99** [comment]
success, wasn't too bad actually
