### ISSUE TITLE
[Questions] Mapview and overlay questions

### ISSUE THREAD

**Issue by hearbeathorror** [osmdroid/osmdroid#1125]
Hi, 
I have some couple of questions: Please assist
1. When i use map listener and delayed listener, move the map and draw the marker , it takes time for the user to be able to move the map and re-center this marker at the new position, is there a way to make it update faster ?

2. I am trying to add simplefastpointoverlay based on the examples in this repo, but it doesnt seem to display it on the map. Is there something that i might be missing? [FIXED - the point style has to be LabeledGeoPoint if simplePointTheme has true set for the second param ]

this is my code for point2 : 

```
SimplePointTheme pt = new SimplePointTheme(points, true);
            SimpleFastPointOverlayOptions options = SimpleFastPointOverlayOptions.getDefaultStyle();
            options.setSymbol(SimpleFastPointOverlayOptions.Shape.CIRCLE);
            options.setRadius(35);
            options.setAlgorithm(SimpleFastPointOverlayOptions.RenderingAlgorithm.MAXIMUM_OPTIMIZATION);
            options.setCellSize(100);

            Paint pointStyle = new Paint();
            pointStyle.setStyle(Paint.Style.FILL);
            pointStyle.setColor(R.color.material_blue);
            pointStyle.setStrokeWidth(200);
            options.setPointStyle(pointStyle);

            mapView.getOverlays().add(new SimpleFastPointOverlay(pt, options));
```
3. Also, setting a custom color to the points only displays black with a transparency. Can we set custom colors? 

4. When zooming or moving the map around, there is some flickering that happens around the dots/points. Is there a way to eliminate this flickering?

The version i use is the snapshot version.

Please assist

Thanks

**Comment by monsieurtanuki** [comment]
Regarding bullet 1, I think I know what you mean and I do think it's annoying. Haven't searched for the speed parameter yet.

Regarding bullet 2, it seems like you fixed it.

Regarding bullet 3, what is the value of `R.color.material_blue`?

Regarding bullet 4, I don't use this class (`SimpleFastPointOverlay`), but here's what I found in the [code comments](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/overlay/simplefastpoint/SimpleFastPointOverlay.java#L23):
````java
/*
 * TODO: support for rotated maps!
 * TODO: a quadtree index would improve rendering speed!
 * TODO: an alternative to the CIRCLE shape, cause this is slow to render
*/
````
My conclusion: the CIRCLE shape you use is notoriously slow, which causes the flickering at each refresh (e.g. panning or zooming). Have a go with SQUARE shape. And beware if your maps are rotated, because it doesn't seem to be supported.
A solution could be to display `Bitmap`s instead of drawing circles, with `Marker`s for instance.

**Comment by hearbeathorror** [comment]
@monsieurtanuki : thank you , i actually moved to a polyline ,and setting the algorithm to none, removes the flicker. 

Is there a way i could move the map and pointer without delay ? Like the way normal taxi apps do. I wonder if we have a camera change listener in osmdroid.

**Comment by hearbeathorror** [comment]
@monsieurtanuki : thanks alot.. 

I managed to make it work without jerks. Just used a marker, and removed it and added it every time the user would move or zoom the app, also i am not centering the map to that location, since the map already knows which location its pointing to. (incase anyone else wants to do this)

Thanks once again
