### ISSUE TITLE
updating markers outside the display and invalidate() causes attempt to load tile

### ISSUE THREAD

**Issue by pasniak** [osmdroid/osmdroid#1130]
## Issue Type

[x] Question
[ ] Bug
[x] Improvement

I have code which draws and updates markers in the user's rough radius of 30miles.  In my test case I draw and update just 1 marker *outside* the display - and call mapView.invalidate() which causes tile load attempt (is it to draw the marker on that tile's background?)

![screenshot from 2018-08-06 06-11-54](https://user-images.githubusercontent.com/19778666/43711105-ab994e86-993f-11e8-9086-de1dcebe0d8b.png)

I had to add the condition below... but that could be handled internally, no?
```
                if (marker!=null && mapView.isVisible(marker.position) == true)
                    mapView.invalidate()
```

**Comment by monsieurtanuki** [comment]
I'm a bit confused, because your code includes code that does not exist, like `mapView.isVisible` and `marker.position`.

That being said, I think what you experience not only is normal but also shouldn't be an issue: from time to time the display is refreshed (anyway the way to know if a marker needs to be displayed is in the display process itself - offset computing and so on), and the refresh is not supposed to take that long (in order to have a smooth map animation).
Is the display refresh slow when you add one marker?

PS: the tile load is due to the fact that when the `MapView.invalidate` is called, the whole display is refreshed. That includes all the tiles. And when some tiles are not in the memory cache, sometimes they can be found in `SqlTileWriter`. In your screenshot, the tile was not found in `SqlTileWriter`.

**Comment by pasniak** [comment]
That is my lean Mapview2 wrapper class instance
class MapView2(context:Context) : MapView(context) {
    fun isVisible(geoPoint: IGeoPoint) = this.boundingBox.contains(geoPoint)

> That includes all the tiles
so that seem to include tiles which are not on the screen.

No, for 1 marker I do not see any perf issues. But there could be 100s of markers updated, I'm yet to simulate this.

**Comment by monsieurtanuki** [comment]
There's a side effect in your `isVisible` method: the marker can be outside of the bounding box but visible on the screen. For instance if it's just outside in the corner but with a centered 21x21 bitmap, we should see something like a 10x10 part of the bitmap.

> so that seem to include tiles which are not on the screen

Correct: not only the displayed tiles are impacted by the refresh, because for instance of the pre-cache, or of the rotation mode. Basically, we're talking about tiles that are related to the current displayed tiles. Or do you see totally unrelated tiles in the logs? That would definitely be a bug.

**Comment by pasniak** [comment]
Re: isVisible - what is my alternative? is there box coverage algo in osmdroid?  
Re unrelated tiles: Right, it is not easy to know... I set isDebugTileProviders true but I do not see the tiles' borders/names on screen....

**Comment by monsieurtanuki** [comment]
Re: isVisible - what is implemented in osmdroid is "before you draw a marker, check first if it is visible" (in `Marker.drawAt`). That way we may skip the draw part, which makes things a bit faster. But that's part of the whole `invalidate` process.

Re: unrelated tiles - if you really want to check if irrelevant tiles are being processed, you need perhaps to add debug logs in `TilesOverlay.OverlayTileLooper.handleTile`. But I don't think you'll find anything.

I would say that you already have your answers for this issue: it's normal to have the whole display refreshed when you add a `Marker`, and that shouldn't be a performance issue anyway.
