### ISSUE TITLE
Android 9 small location icon 

### ISSUE THREAD

**Issue by JonasDaWi** [osmdroid/osmdroid#1209]
## Issue Type

[ ] Question
[x] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
On Android 9, the default location/bearing icon is much smaller than on older Android versions

## Environment
Android 9, Pixel & S9+
### If it's a bug, version(s) of android this affects:
Android 9

### Version of osmdroid the issue relates to:
6.0.3

**Comment by monsieurtanuki** [comment]
I guess it's related to your screen dpi.
I'm not sure which icon you're referring to; do you know the name of the file, or can you post a screenshot?

**Comment by JonasDaWi** [comment]
On the same device the icon is much smaller on Android 9 than in Android 8. You can see this in the osmdroid mapviewer sample app (More Samples/Location/Directed Location).

**Comment by monsieurtanuki** [comment]
I still believe it has to do with dpi, as the `direction_arrow` icon only had one version: 40x40 pixels.
Just PR'ed (#1212): use of another icon, with a version for each dpi folder.
@JonasDaWi Please tell me if it works.

**Comment by TFreudi1** [comment]
The direction_arrow is working now, but the "Dont move person-symbol" is very small and the standard marker icon too. The strange thing is that the same apk works in all Simulators up to 8.1 but not in Pie 
It Looks like the Android:anyDensity feature is not working anymore in Pie but I did'nt found something about it on the net.

**Comment by monsieurtanuki** [comment]
@TFreudi1 "Dont move person-symbol": do you mean ![person](https://user-images.githubusercontent.com/11576431/53303125-04832000-3867-11e9-8ee1-733dab434bb6.png)?
"Standard marker": do you mean ![marker_default](https://user-images.githubusercontent.com/11576431/53303139-3300fb00-3867-11e9-8a12-6d3f295a5240.png)?

**Comment by TFreudi1** [comment]
yesVon meinem Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: monsieurtanuki <notifications@github.com> Datum: 24.02.19  19:06  (GMT+01:00) An: osmdroid/osmdroid <osmdroid@noreply.github.com> Cc: TFreudi1 <TFreudi1@gmx.de>, Mention <mention@noreply.github.com> Betreff: Re: [osmdroid/osmdroid] Android 9 small location icon  (#1209) @TFreudi1 "Dont move person-symbol": do you mean ?
"Standard marker": do you mean ?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/osmdroid/osmdroid","title":"osmdroid/osmdroid","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/osmdroid/osmdroid"}},"updates":{"snippets":[{"icon":"PERSON","message":"@monsieurtanuki in #1209: @TFreudi1 \"Dont move person-symbol\": do you mean ![person](https://user-images.githubusercontent.com/11576431/53303125-04832000-3867-11e9-8ee1-733dab434bb6.png)?\r\n\"Standard marker\": do you mean ![marker_default](https://user-images.githubusercontent.com/11576431/53303139-3300fb00-3867-11e9-8a12-6d3f295a5240.png)?\r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/osmdroid/osmdroid/issues/1209#issuecomment-466800600"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/osmdroid/osmdroid/issues/1209#issuecomment-466800600",
"url": "https://github.com/osmdroid/osmdroid/issues/1209#issuecomment-466800600",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by TFreudi1** [comment]
Yes, exactly that. But I also have "private" marker symbols only in the drawable directory which were scaled on all pre Pie versions.

**Comment by TFreudi1** [comment]
There should be an manifest entry
android:anyDensity which is true by default this should control the behaviour, but also setting this explicitly to true did'nt help on Pie.

**Comment by monsieurtanuki** [comment]
I didn't even know there was such thing as "anyDensity".
If you find a general fix please share it with us, but I assume the definitive fix is to use all the dpi folders.

**Comment by TFreudi1** [comment]
This is was Google suggest, but it is a bit strange that still have the passages in their documentation that says that the OS autocalculate the dimension of bitmaps that resides in the standard drawable directory, if nothing is available in the *dpi Directorys.
And this is still working on Androids < 9 ! It is really easily to test yourserl, take your sample App and run it on an emulator with Android 28 an run the same on a version below. I will try to make a sample App without osmdroid maybe it leads into an answer. For sure I will tell you the results.

**Comment by TFreudi1** [comment]
https://developer.android.com/training/multiscreen/screendensities

**Comment by TFreudi1** [comment]
… Pre-scaling of resources (such as bitmap drawables) 
Based on the density of the current screen, the system uses any density-specific resources from your app. If resources are not available in the correct density, the system loads the default resources and scales them up or down as needed. …..

Auto-scaling of pixel dimensions and coordinates 
You can disable pre-scaling dimensions and images by setting android:anyDensity to "false" in the manifest or programmatically for a Bitmap by setting inScaled to "false"

**Comment by TFreudi1** [comment]
In an simple app all the symbols are properly automaticly (up/down) sized if the they reside in the drawable directory, so it is a problem in osmdroid+Pie , I did'nt found a simple solution, the best should be what you already wrote: put the correct symbols in the dpi-directories. But I also have quick solution unitl you did that.
For the marker symbol I wrote in may Startcode:
` if (android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
                Drawable d = ResourcesCompat.getDrawable(getResources(), R.drawable.marker_default, null);
                Bitmap bitmap = ((BitmapDrawable) d).getBitmap();
                Drawable dr = new BitmapDrawable(getResources(), Bitmap.createScaledBitmap(bitmap, (int) (48.0f * getResources().getDisplayMetrics().density), (int) (48.0f * getResources().getDisplayMetrics().density), true));
                marker.setIcon(dr);
            }` The effect is exactly the same as the the autosize of the os in Android < Pie.

**Comment by monsieurtanuki** [comment]
@TFreudi1 Thanks for your solution, it's good to know that.

Unfortunately there are two problems for this current issue:
* the icons won't look as good as possible for xxxhdpi, because it will only be a (very) stretched version
* the fact that we have both `drawable` and `drawable/*dpi` makes it lousy - in some cases (like this issue) we need to process the bitmap, and in other cases we don't. How should we know when to apply the additional bitmap stretch process, as all icons are accessed through `R.drawable` ?

As far as osmdroid is concerned, I guess the right solution would be to use the `drawable/*dpi` folders (we won't avoid the possible "stretched look" effect).
As I only have 48x48 pixel icons, in first approach I'll just stretch them into the right size, anyway I don't know how to draw correctly those icons on larger sizes.

Working on it...

Then one day I guess someone will create the issue "some osmdroid icons really look stretched on my high density smartphone". But it's less embarrassing than tiny icons.

**Comment by monsieurtanuki** [comment]
PR'ed #1282
@TFreudi1 Would you test it?
Btw did you try to put your unique icons in `drawable/mdpi` instead of `drawable`?

**Comment by TFreudi1** [comment]
I agree with you, and the symbols are realy tiny, so make them looked stretch in my eyes are the less worse solution :-) I'm very untalented in arts, especally create icons and bitmaps but put them in the DPI folders  is the only thing what you can do, don't change it in Code. It makes me a bit unsatisfied that I didn't find any line like:
if (android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.P)
in the osmdroidsource related to the problem.

**Comment by TFreudi1** [comment]
Ok I will try it … and I didnt try to put it in the mdpi folder, but i will do

**Comment by TFreudi1** [comment]
![osmdroiddpi](https://user-images.githubusercontent.com/4739177/53372018-155c9000-3952-11e9-9fe2-8baf565b0f66.jpg)
This is much better, left you see bug/1209-2, Right is 6.1.0-SNAPSHOT

**Comment by monsieurtanuki** [comment]
@TFreudi1 Thanks for your test, it's much better.
It's strange to see that the `osm_ic_center_map` icon (top-right) looks bigger than `person` and `marker_default`, though they have the same pixel size.
Questions:
* are the `person` and `marker_default` icons big enough for you?
* how come they still look smaller - did you enlarge the `osm_ic_center_map` icon in the context of your app?

**Comment by TFreudi1** [comment]
@monsieurtanuki Person+marker Default can be a bit bigger thats true 
osm_ci_center_map resides in the DPI* folders, my own "Go to marker" symbol have the same sizes.
mdpi = 48 Px, hdpi = 72 Px …. xxxhdpi = 192 Px. 
The new person symbol have the same sizes so indeed it is the next strange thing that they are a bit different.
Person is drawing by MyLocationNewOverlay and marker is laos an mapView Overlay. The both Buttons in opposite, are placed in the layout  as image button, so maybe the mapView has some kind of "zoom" function ?
This is my layout:
 <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical">

        <org.osmdroid.views.MapView
            android:id="@+id/mapview"
            android:layout_width="fill_parent"
            android:layout_height="fill_parent"
            >
        </org.osmdroid.views.MapView>

        <ImageButton android:id="@+id/ic_center_map" android:background="#00ffffff" android:layout_height="wrap_content" android:layout_width="wrap_content" android:cropToPadding="true" android:contentDescription="@string/activity_karte_zentrieren" android:layout_marginRight="10dp" android:layout_marginTop="10dp" android:layout_alignParentEnd="true" android:layout_alignParentRight="true" android:layout_alignParentTop="true" android:layout_marginEnd="10dp" android:src="@drawable/ic_center_map"/>
        <ImageButton android:id="@+id/ic_move_sym_to_pos" android:background="#00ffffff" android:layout_height="wrap_content" android:layout_width="wrap_content" android:cropToPadding="true" android:contentDescription="@string/activity_unfallsymbol_auf_aktuelle_position" android:layout_marginTop="10dp" android:src="@drawable/move_symbol2own_position" android:layout_alignStart="@+id/ic_center_map" android:layout_alignLeft="@+id/ic_center_map" android:layout_below="@+id/ic_center_map"/>
    </RelativeLayout>

**Comment by monsieurtanuki** [comment]
@TFreudi1 A possible test about your "`ImageButton` bigger display" theory: see what a `person` icon would look like inside the `ImageButton`.

**Comment by TFreudi1** [comment]
I would say my theory ist not bad :-)
![osmdroid](https://user-images.githubusercontent.com/4739177/53402549-38b72780-39b2-11e9-8797-b6fd1400e62b.jpg)

**Comment by TFreudi1** [comment]
I only cut it, I did'nt zoom anything, I swore, but in this you may see it better::
![osmdroid2](https://user-images.githubusercontent.com/4739177/53402752-9ba8be80-39b2-11e9-9d04-ade8342f2827.png)

**Comment by monsieurtanuki** [comment]
@TFreudi1 Thanks for your explicit screenshots.

I'd say that the marker is big enough, as there can be dozens of markers on the same screen.

Is the person icon a bit small? Perhaps, but I cannot make it bigger (I could stretch to a taller person, but the shadow wouldn't fit).

The issue was about some _default_ icons being _tiny_: they now have a decent size and a size that matches the device dpi. And there's always the possibility to use your own icons anyway.

On my smartphone the icons look OK:
![screenshot_2019-03-02-16-56-56](https://user-images.githubusercontent.com/11576431/53684397-17856c80-3d0d-11e9-862e-61e14988890a.png)
![screenshot_2019-03-02-16-59-51](https://user-images.githubusercontent.com/11576431/53684401-1bb18a00-3d0d-11e9-88e8-83c78ca61704.png)

Conclusions:
* I guess the Android *dpi bitmap management is not 100% satisfactory (icons may look a bit small on some devices and a bit big on other devices)
* But it's beyond osmdroid's scope
* I close the issue now, but feel free to reopen it or to comment

**Comment by TFreudi1** [comment]
Absolutly OK!

**Comment by jpmeijers** [comment]
I was also affected by this issue on Android 9 using v6.0.3. Switching to vector drawables solved the issue for me and also gave a much nicer non-pixelated result.

**Comment by TFreudi1** [comment]
I also have "own" symbols as vector drawables but have to raise the android:height/width, android:viewportHeight/Width in v 6.0.3 to get the same size in Pie as in pre Pie versions. 
And than, logically the next questions is, do you have the person symbol and the marker symbol as drawable ? If so I guess monsieurtanuki and the osmdroid crew would be very happy to get it.
