### ISSUE TITLE
Overlay.draw() signature change is quiet breaking change

### ISSUE THREAD

**Issue by pasniak** [osmdroid/osmdroid#1255]
This is a quiet breaking change: /!\ Maybe remove @Deprecated from Overlay.draw() this so wrong code would not build?

```
	@Deprecated
	public void draw(final Canvas pCanvas, final MapView pMapView, final boolean pShadow) {
		if (pShadow) {
			return;
		}
		draw(pCanvas, pMapView.getProjection());
	}

	/**
	 * @since 6.1.0
	 */
	public void draw(final Canvas pCanvas, final Projection pProjection) {
		// display nothing by default
	}
```

## Issue Type
[x] Question
[x] Bug
[x] Improvement
[ ] Build system related
[ ] Performance
[x] Documentation

## Description and/or steps/code to reproduce the problem

My custom vectorOverlays inheriting from Overlays quietly stopped being drawn.  I did not break in  draw() anymore.

I was working on c956fe1d923916d1c362994918e31b74c7d45174 (bug/#1209 - using a resource for direction icon on each dpi folder (#1212) monsieurtanuki* 12/5/18 10:52 PM)
and that happened when I switched to current master (473046516b73f16b9e4709500fd2171052d7ae9e as of 1/6/19).

### Version of osmdroid the issue relates to:
6.1.0

**Comment by spyhunter99** [comment]
it shouldn't have broken anything, only a new method was added. Is your build setup to fail if you are using deprecated methods or something?

**Comment by spyhunter99** [comment]
oh....i think i see what happened. I bet only the new method is called, not the new one.

**Comment by pasniak** [comment]
No, I have bunch of deprecated Android API calls.  If such breaking change happens it would be great to get a 6.1.0-Beta build (keep 3 env in sync so not having to build OsmDroid 3 times woudl be nice :+1: )

**Comment by spyhunter99** [comment]
It shouldn't be a breaking change. The api probably won't be removed for several versions at least. The 'at' deprecated is just a notification that it will eventually go away

**Comment by monsieurtanuki** [comment]
My bad: I was a bit too enthusiastic with my latest changes.

My idea was to say: let's create `Overlay.draw(Canvas, Projection)`, implement here the drawing code, deprecate `draw(Canvas, MapView, boolean)` and let it call `draw(Canvas, Projection)` by default.
Why? Because for the new map snapshot feature we cannot rely on a `MapView`, and in most cases a `Projection` is enough.
Was it supposed to be safe? Yes, because the legacy code would continue to override `draw(Canvas, MapView, boolean)`, and the latest code would override `draw(Canvas, Projection)`, that will be called by the default implementation of `draw(Canvas, MapView, boolean)`.

My mistake is that in `DefaultOverlayManager` I totally bypassed `Overlay.draw(Canvas, MapView, boolean)` and directly called `Overlay.draw(Canvas, Projection)`: the legacy code is not called anymore.

Sorry about that. I'll fix that today...

**Comment by monsieurtanuki** [comment]
Just PR'ed in #1253

**Comment by monsieurtanuki** [comment]
@pasniak Is that OK now?
