### ISSUE TITLE
Problem with animated map rotation

### ISSUE THREAD

**Issue by mlendl** [osmdroid/osmdroid#1256]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[ ] Question
[x] Bug
[x] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

I am using method mapView.getController().animateTo() to rotate map with animation. Problem is, if I change map orientation e. g. from 179 to -179 the whole circle (358 degrees) is done. If I use unsigned values, it is the same, e. g. from 359 to 1. I have no idea how to solve it on my side, I think, it should be solve in the Osmdroid.

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.0.3

**Comment by monsieurtanuki** [comment]
Fair enough. I guess the solution would be to add a `Boolean` parameter to `MapController.animateTo`, something like `isClockwise`, with a default value of `Boolean.TRUE`.
Then it would be the developer's problem to pre-compute the value of this parameter if needed in order to ensure the animation goes in the "correct" direction.
@mlendl Does that make sense?

**Comment by mlendl** [comment]
I think no. We never want to rotate the whole circle. The solution could be
always rotate the shortest distance.

**Comment by monsieurtanuki** [comment]
Then the default value (`null`) could be the shortest distance, `Boolean.TRUE` an explicit clockwise and `Boolean.FALSE` an explicit anticlockwise.

**Comment by mlendl** [comment]
OK, that's perfect solution

**Comment by mlendl** [comment]
Seems to be OK
