### ISSUE TITLE
After zooming in no map is visible.

### ISSUE THREAD

**Issue by niccokunzmann** [osmdroid/osmdroid#1259]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[X] Bug

## Description and/or steps/code to reproduce the problem

When I open the app, I open the first map view.
Then, I scroll using the fingers.
Then, I see white squares.

## Environment

Diagnostics -> Permission all to yes
Extrernal Storage State: not available

### If it's a bug, version(s) of android this affects:

Android 2.3.5 

### Version of osmdroid the issue relates to:

6.0.1 release

**Comment by spyhunter99** [comment]
is that correct? you are using android version 2.3.5? Ginger bread? It's possible some newer APIs have sneaked in there. While the min sdk is 8, we've stopped testing on it since android pulled all the avd's for the earlier versions. I'll see if i can get the genny motion vm running for 2.3.7. It's the oldest they have

**Comment by spyhunter99** [comment]
nope you are out of luck, earliest image i have with geny is 4.1. Sorry. Best i can offer is turn on debugging and watch logcat to see if there are any obvious problems

**Comment by spyhunter99** [comment]
reopen if it's still a problem, although there isn't much we can do about it. update your device?
