### ISSUE TITLE
Tile gap using WMS under certain conditions

### ISSUE THREAD

**Issue by RUANHAOANDROID** [osmdroid/osmdroid#1264]
[map image](https://upload-images.jianshu.io/upload_images/530023-25763414274171a6.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by RUANHAOANDROID** [comment]
Used WMSTileSource

**Comment by monsieurtanuki** [comment]
Regardless of the actual issue, your link isn't accessible.

> 403 Forbidden
You don't have permission to access the URL on this server.
Powered by Tengine 

Just attach your snapshot inside your github post:
> Attach files by dragging &amp; dropping, selecting them, or pasting from the clipboard.

**Comment by RUANHAOANDROID** [comment]
![image](https://user-images.githubusercontent.com/10151414/52679376-e0bf0080-2f6f-11e9-9fa2-ae6287c6727c.png)

**Comment by monsieurtanuki** [comment]
When we draw the tiles we stretch them: e.g. we download 256x256 tiles from the provider, and we stretch them on the screen in order to fit the actual display (according to screen density and floating point zoom level).

My initial thought was: maybe the tile display size on the screen is not good: we should stretch to 400x400 tiles, and not to 399x399, there's a problem when rounding.
But if that was the case, you should have the same problem on the height, and see basically map squares with a 1 pixel wide border. Strange...

I don't know anything about WMS tile source. Fun fact: in the demo "More samples / tilesources / WMS source" I can see the same repeated "black vertical lines", but that's about showing the "main" longitudes (e.g. integer values). Could it be related to your issue?

**Comment by RUANHAOANDROID** [comment]
There is a black line on the right side of the picture using "SRS=EPSG%3A90091".
Normal when loading "CRS = EPSG%3A4326" with "openlayer"。

**Comment by RUANHAOANDROID** [comment]
This is my source
```java
String[] serverURL = {"http://192.168.28.231:9090/beyonserver/beyondb/wms?"};
WMSTileSource wmsTileSource = new WMSTileSource("beyonserver", serverURL , "beyondb%3Aimg_glob_0_7", "1.1.1", "EPSG:900913", "", 256);`
mapView.setTileSource(wmsTileSource);
```

**Comment by spyhunter99** [comment]
i'm not familiar with that map server, but i never saw an issue like this with geoserver. sorry but much i can do about it.

**Comment by RUANHAOANDROID** [comment]
Thank you
