### ISSUE TITLE
getController().animateTo(location) no longer triggers onScroll() event.

### ISSUE THREAD

**Issue by xyz32** [osmdroid/osmdroid#1267]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[ ] Question
[X] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
In 6.0.3 the getController().animateTo(location) call will no longer trigger the onScroll event of a MapListener.
```
mapWidget.addMapListener(new DelayedMapListener(new MapListener() {
            @Override
            public boolean onScroll(ScrollEvent event) {
                System.out.println("--------onScrollEvent");
                if (event.getX() != 0 || event.getY() != 0) {
                    updatePOIs(true);
                }
                return false;
            }

            @Override
            public boolean onZoom(ZoomEvent event) {
                System.out.println("--------onZoomEvent");
                updatePOIs(true);
                return false;
            }
        }));
```

and this is the code that scrolls the map:
```
public void centerOnGoePoint(GeoPoint location) {
        osmMap.getController().animateTo(location);
    }
```
Used to work with 6.0.0.

Thanks.

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.0.3

**Comment by monsieurtanuki** [comment]
@xyz32 Actually it still works. But you're right, recently changes were applied.

This is the way I tested it (in 6.1.0 snapshot, more or less): I added the `addMapListener` code you suggested to the "More Samples / Events / Animate To" demo.
The result is that the `onScroll` is triggered, BUT with event's X and Y at 0.
I guess that within your tests, you see the `println` (I myself use `Log.e` but the result is equivalent), but as X and Y are 0, you don't play `updatePOIs`.

In your code you test `event.getX() != 0 || event.getY() !=0`, which made sense in previous osmdroid versions.
The scroll values used to mean something - basically it was about applying a scroll (`int` values) to a `View`.
Now, for different reasons, including the fact that the scroll values can be `long` (zoom level up to 29), we don't really use the standard Android `View` scroll feature.

We still use the `ScrollEvent`, but as we don't think about map positioning as `int` scroll values but rather as `GeoPoint` map center, we create a `ScrollEvent` _[with dummy event values of 0](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/MapView.java#L1808)_.

In order to fix your issue, you should skip the (0,0) test in your code - as we create a `ScrollEvent` only if the map center changed and it will be created with (0,0).
This is the quick fix for you.

Another way would be to either put non-0 dummy values in the event, or to compute half-meaningful scroll values, but I don't believe it would make sense nowadays.

@xyz32 Could you try the quick fix I suggest?

**Comment by xyz32** [comment]
That works, thanks
