### ISSUE TITLE
Markers rotation wrong when map rotated

### ISSUE THREAD

**Issue by pasniak** [osmdroid/osmdroid#1300]
## Issue Type

[ ] Question
[x] Bug
[x] Improvement

## Description and/or steps/code to reproduce the problem

In More Samples, choose Long Press to Plot Marker, add a Marker (small person) at the Antarctic border horizontal line. Note the person's head is up (north) and legs are down. 

Now, touch-rotate the map 90 degrees. The small person is rotated 180 degrees.  I'd expect it was rotated 90.

### Version of osmdroid the issue relates to:

6.0.3

**Comment by spyhunter99** [comment]
this would mean that the marker classes's rendering isn't quite right.  bummer

**Comment by monsieurtanuki** [comment]
@pasniak
I couldn't reproduce this issue.
Probably duplicate with #1181.
Solved in 6.1.0: can you try with the latest osmdroid release?

Additional thoughts
Perhaps you assume that the marker should _follow_ the map. If the marker is a "|", you expect it to be a "_" when your rotate the map 90°.
Other users may think that if the marker is a burger, there's no reason to rotate the burger according to the map orientation (unless you like reversed burgers). That's the current implementation.
If that makes sense, we should add a "boolean followMapOrientation" in Marker, in order to handle both (legitimate) cases. Does that make sense?

**Comment by spyhunter99** [comment]
it seems to work as expected the marker's orientation does not rotate with the map to aid in readability. you can however set the marker's rotation equal to the map's orientation. maybe that will you out. Current behavior is the intended behavior

**Comment by MKergall** [comment]
Note that - trying to stick to Google Maps API for Android - osmdroid Marker supports 2 combinations about marker orientation: 
1) Flat or Billboard (setFlat) => default is billboard. 
2) Rotation (setRotation)

see https://developers.google.com/android/reference/com/google/android/gms/maps/model/Marker.html

Now, we may have a particular issue at map limits (Antartic border).

**Comment by monsieurtanuki** [comment]
@MKergall OK for the existing flat/billboard set-up.
But I don't understand the Antarctica side-effect. Something like a Marker in the deep south being partially drawn in the highest north?
