### ISSUE TITLE
Markers are not resized on Zoom

### ISSUE THREAD

**Issue by neoacevedo** [osmdroid/osmdroid#1359]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[x] Question
[x] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.0.3

___
I add a marker at this mode:
```java
marker = new Marker(map);
marker.setDefaultIcon();
marker.setIcon(getResources().getDrawable(R.drawable.location));
marker.setPosition(new GeoPoint(latlong.latitude, latlong.longitude));
marker.setTitle(getString(R.string.my_location));
map.getOverlays().add(marker);
```
When I do zoom, the marker remains its size. So, when I zoom out, the marker covers a part of the map tiles. Is OSMDroid able to resize the marker just like Google Maps?

**Comment by monsieurtanuki** [comment]
@neoacevedo I don't consider it's a bug. It may not work like Google Maps, though (I can't tell, I don't use Google Maps).

If I may rephrase your issue, it could be something like: "I want the marker to potentially have several icons/sizes - depending on the zoom level - because sometimes it does not make any sense to keep a full sized icon for city related markers when we are at the zoom level of the whole country". Does that make sense?

**Comment by MKergall** [comment]
@neoacevedo osmdroid Markers keep their size (in screen pixels) when zooming, juste like Google Maps markers. 

If you want to have a bitmap on the map that keeps it size (in map coordinates) when zooming, you can use a GroundOverlay (the one from osmdroid or the one from OSMBonusPack, as you prefer).

**Comment by spyhunter99** [comment]
yup, working as intended. To get the resizing effect, you can either extend marker, or add a map events listener and replace the icon on all markers when zoom thresholds are crossed
