### ISSUE TITLE
Infinite re-download of the same tiles

### ISSUE THREAD

**Issue by tonykaram1993** [osmdroid/osmdroid#1489]
## Issue Type

 Bug

## Description and/or steps/code to reproduce the problem

On monday (4 days ago) we started getting reports that the app is using a huge amount of data, we were able to reproduce the issue on our test devices. It turns out that osmdroid was the issue. The issue is that some tiles (it seems to be random), mainly 3 or 4 tiles, keep getting re-downloaded over and over again:

![image](https://user-images.githubusercontent.com/3901162/73008087-77e63680-3e16-11ea-8b34-e21f18e16ce7.png)

We also noticed that when fully zoomed in on the map, the issue does not manifest itself. It happens mostly when zoomed out and consistently. We tested this in multiple locations scattered around the globe so it is not location dependent.

### If it's a bug, version(s) of android this affects:

Tested on OnePlus OxygenOS 10+ and Google Pixel Android 10+ and Samsun A10 Android 5.1.1

### Version of osmdroid the issue relates to:

5.6.5

Not sure what more information you might need, let me know if I can provide any further details.

**Comment by monsieurtanuki** [comment]
@tonykaram1993 The way you describe things, it looks like:
* your app uses version 5.6.5 of osmdroid
* your app has been working OK for months with the same osmdroid code and settings
* your app started experiencing the infinite re-downloads 4 days ago

My suggestions:
* run tests with a different tile source
* run tests with the latest version of osmdroid

**Comment by tonykaram1993** [comment]
@monsieurtanuki You are correct.

Regarding your suggestions, I just tried using OpenTopo as tile source and the problem vanished. Unable to test with latest version of osmdroid as upgrading to version 6+ breaks stuff so its not an easy task.

Any clues why MAPNIK is where the problem occurs?

**Comment by monsieurtanuki** [comment]
@tonykaram1993 About MAPNIK, I have a hunch: the problem might be with the tile file expiration date. I believe it's possible to override the expiration date in general, or to add time to it. You should try something with `DefaultConfigurationProvider.setExpirationExtendedDuration` for instance. Tell me if it works.

When we're done with this issue, please tell me the kind of problems you would have upgrading to the latest osmdroid version.

**Comment by tonykaram1993** [comment]
I did mess with the expiration duration before and it did not help.

Alright, so I did upgrade to 6.1.5 and the issue seems to be fixed so far (needs extensive testing before I can 100% confirm).

Will post an update here after extensive testing is done.

**Comment by tonykaram1993** [comment]
@monsieurtanuki Okay, so a small update. We did not end up updating osmdroid to version 6, instead we used 
 `org.osmdroid.config.Configuration.getInstance().setExpirationOverrideDuration(604800000L);` and it seems to have fixed our problems. Any clue what is happening here?

**Comment by monsieurtanuki** [comment]
@tonykaram1993 Sorry I pointed you to the wrong `setExpirationDuration` method.
My idea was that the tile expiration time, taken from the URL downloaded file, suddenly got wrong (the error coming from the tile source server). As we use the **F**ile expiration time to compute the **T**ile expiration time, if for instance the file expiration time is in the past, then so is the tile expiration time, which triggers the "oh this tile is expired, I need to fetch the new version" snowball behavior.
If you have time, get the http header of a tile file and see its expiration time. If the time is wrong (as I supposed), then it would be worth contacting the tile source team.
Would that make sense to change our algorithm in order to be more resilient _systematically_? I'm not sure 100%. Though something like a `setResilientMode(boolean)` could be helpful.

**Comment by pasniak** [comment]
I suggest more debug logging. I did add HTTP header logging in my local build.

**Comment by monsieurtanuki** [comment]
Seems to be solved. @tonykaram1993: don't hesitate to reopen the issue or to open a new one if needed.
