### ISSUE TITLE
flood of draw() invocations on mapview overlays

### ISSUE THREAD

**Issue by mikebravoyes** [osmdroid/osmdroid#1498]
#902  Issue Type

[x] Question
[ ] Bug
[x] Improvement
[ ] Build system related
[x] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

I have written a map application with osmdroid, which uses several overlays, standard ones (CopyrightOverlay, ScaleBarOverlay, etc.) plus own implementations (e.g. for a north arrow). All these classes consist of a constructor and a function "draw()". I found that each draw function is invoked several times per second, even for static conditions (no zoom or scroll is applied, no invalidate() is called, no android life cycle events occur). I don't understand, why this happens and what is it good for.

I mean, the app works fine, but has a constant CPU load in the background, slowing down the app slightly. What's the point in updating the copyright notice several times per second?

## Environment

Huawei P10 Lite

### If it's a bug, version(s) of android this affects:

Android 8.0.0, SDK 26

### Version of osmdroid the issue relates to:

6.1.2

**Comment by monsieurtanuki** [comment]
Actually it's not supposed to happen. Calls to draw can be frequent though while your tiles are being downloaded. Or if the tile file expiration date is not correct (the tile file is correctly downloaded but immediately considered expired, which triggers downloads and therefore calls to draw).
My suggestions (for tests):
* try another tile source
* get rid of all overlays (maybe one if them is the root of the issue)
* use the latest osmdroid code

**Comment by mikebravoyes** [comment]
@monsieurtanuki: Thanks for your hints. I forgot to mention, that the download of files has been completed.

```
// check completeness of map tiles
TileStates tileStates = mapView.getOverlayManager().getTilesOverlay().getTileStates();

// evaluate the tile states
if (tileStates.getTotal() == tileStates.getUpToDate())
{
    // map is loaded completely

}
else
{
    // loading is still in progress

}
```

See my comment on https://stackoverflow.com/questions/17079359/detect-if-the-osm-mapview-is-still-loading-or-not-in-android.

But now to your suggestions:

> •	try another tile source

I am using different tile providers/sources: “tile.openstreetmap.org” (MAPNIK, HIKEBIKEMAP, OpenTopo, etc.) and “tile.thunderforest.com” (cycle, transport, outdoors). The effect is always the same.

> •	get rid of all overlays (maybe one if them is the root of the issue)

The following “standard” overlays are used in my app: TilesOverlay, CopyrightOverlay, LatLonGridlineOverlay2, CompassOverlay, ScaleBarOverlay, RotationGestureOverlay, MinimapOverlay, Polyline, Marker,

plus some self-defined overlays: NorthArrowOverlay, TextOverlay, CircleOverlay, RectOverlay.

The source of evil seems to be the CompassOverlay. When it is disabled from the start of the app, everything is fine. After activation of the compass, it continuously causes the cyclic invocation of draw() in every overlay, probably produced by an invalidate() for the whole screen, not only its own display region. However, after the compass overlay is switched OFF during runtime, the effect does not (!) disappear, it remains.

> •	use the latest osmdroid code

That is hard-core stuff, don’t know how to do this. But it’s obviously not necessary any more, as the wrongdoer has been identified above.

Thanks for your support. Perhaps it is possible to improve the CompassOverlay accordingly.

**Comment by monsieurtanuki** [comment]
@mikebravoyes I don't use `CompassOverlay` myself.

From what I can see in the code, [`invalidateCompass`](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/overlay/compass/CompassOverlay.java#L140) is called by [`onOrientationChanged`](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/overlay/compass/CompassOverlay.java#L318), and is actually at most executed every half second.
What could be changed/optimized:
* have the display refresh of the compass actually refresh only the pixel area of the compass, which I believe we don't do (when we refresh the display we always refresh the whole screen) - which would cause a smaller flood of draws (same frequence, but less draws as now each time)
* use a parameter instead of the half second - depending on the accuracy needed (less frequent, but the same number of draws as now each time)
* store the previous bearing value - if the current value matches the previous value (careful - we're talking about `float`s), don't refresh (less frequent, but same number of draws as now)
* display the compass on top of the map, with a `View`, like we do with `Marker`'s info window

**Comment by mikebravoyes** [comment]
@monsieurtanuki 
That sounds excellent! If I had the choice, I would select the options 1 (refresh only the pixel area of the compass) and 3 (check, if orientation has changed). But of course, it's up to you.

**Comment by monsieurtanuki** [comment]
@mikebravoyes Option 1 is not that easy development-wise - and I guess you would have to upgrade to the next latest osmdroid code, which means not easy to install and test.
Option 3 is rather easy, and you'd be able to test it by just copying the new `CompassOverlay` code to a custom `MyCompassOverlay` class.

**Comment by mikebravoyes** [comment]
@monsieurtanuki 
Don't worry! As I know the reason for this behaviour now, I can live with it and wait for the next version of osmdroid.

**Comment by monsieurtanuki** [comment]
@mikebravoyes Well, if options 2 and 3 happen to work, that would be a very good start.

Regarding option 1, I guess it should be a distinct issue. It may even not fix the current issue: there would still be a flood of map.draw(), where every `Overlay` would be checked before drawing, instead of systematically drawn. Of course better performances, but good enough for your app?

Reading again your issue description: "each draw function is invoked several times per second".
I know "several" starts with 2, but given that there's a .5s interval limit, it shouldn't be more than 2 times per seconds, should it?

**Comment by mikebravoyes** [comment]
@monsieurtanuki 
As I said, the performance is good enough - already now. (But of course, there is always room for improvement.)

Concerning the exact timing, I couldn't resist to make some data logging over 10 minutes with my app "Sensor Recording", with the smartphone laying still on the table. The result was surprising: There is always a pair of two invocations for draw(). My first idea was, that there is one call with shadow = true, and one with shadow = false. But this is not the case - shadow is constant false.
The delta time between two calls is always short, long, short, long, etc. The two times are varying over time, but their sum is always 500 msec (more or less). I have processed the data with MS Excel and created some diagrams.

Diagram 1 shows the "delta time" between calls (blue dots) plus the "sum of 2" consecutive calls (red dots). Vertical scale is in msec. 
![TimeDiagram](https://user-images.githubusercontent.com/6436590/75430420-94ace700-594b-11ea-93a5-e27894d16829.png)

Diagram 2 shows the histograms (frequency distributions) of the two data sets above. Horizontal scale is in msec.
![Histograms](https://user-images.githubusercontent.com/6436590/75431798-b0b18800-594d-11ea-964b-951cc2468d67.png)

Have fun with the interpretation of this behaviour.

**Comment by monsieurtanuki** [comment]
@mikebravoyes Hmm, there's no "shadow=false" invocation for `CompassOverlay` since 14 months...

I've just coded a new version of `CompassOverlay`, that you can find in #1502.
You may not be able to merge it into your 6.1.2 code - if necessary, just use the code around `mLastRenderLag` and `mAzimuthPrecision`.
Could you please play with it and tell me if it works? Thanks!

**Comment by mikebravoyes** [comment]
That was a misunderstanding. I was not able to measure times in CompassOverlay itself. The measurement was performed in one of my own overlays. In stable conditions (no zoom, no scroll, etc.), its draw function is triggered periodically, as soon as the compass overlay is activated, otherwise not. As mentioned, this happens with an update rate of approx. 4 events per second (at irregular intervals).

To test your new version, I need some time to figure out, how this can be done. So far, I have no experience with merging new code into an existing library. Is there a cooking recipe somewhere?

**Comment by monsieurtanuki** [comment]
My suggestion:
* copy whatever version of class `CompassOverlay` you see in your version of osmdroid, and call it `MyCompassOverlay`
* edit it and report [the changes I made](https://github.com/osmdroid/osmdroid/commit/d2a1d00f1ab1856fbffe7f26415f739f32e03136)
* use `MyCompassOverlay` in your code - you will even be able to log the frequency of callback and display refresh directly caused by the compass

**Comment by mikebravoyes** [comment]
@monsieurtanuki 
According to your proposal, I have taken over the existing class as MyCompassOverlay and have modified the related code. Furthermore, I again made some time measurements with the functions "onOrientationChanged()", "invalidateCompass()" and  "draw()". The results were very similar to those from yesterday. 

A detailed investigation of the double calls of draw() revealed, that the failure was on my side: I have created two instances of CompassOverlay by mistake - each of them triggered by onOrientationChanged(). That was the reason for the double invocation of the whole chain. After I changed that in my app, everything was fine concerning this "doubling" behaviour.

That was the good news. But there is still the following problem:

As far as I understood the code, the function invalidateCompass() does a call  mapView.postInvalidateMapCoordinates(left, top, right, bottom), which should mark the compass area on the screen as "dirty rectangle". 

However, the draw() functions of all the other overlays (CopyrightOverlay, LatLonGridlineOverlay2, ScaleBarOverlay, MinimapOverlay, etc. plus my self-defined overlays: NorthArrowOverlay, TextOverlay, RectOverlay, ...) are triggered as well, even if they are far away from the compass region. Does that mean, the "dirty rectangle" specification for invalidate() is only valid for its own layer? Then it would be useless, as most of the map components are located in their respective specific overlays. See the following screenshot as example:

![Screenshot_Helgoland](https://user-images.githubusercontent.com/6436590/75626038-448c8980-5bc4-11ea-8636-bba01646612f.jpg)

**Comment by monsieurtanuki** [comment]
@mikebravoyes If I remember well we don't deal with the "dirty rectangle"s at all (maybe we did a long time ago, which would explain the parameters in the invalidate call), we always refresh the whole screen. And changing that would induce a change in all the `Overlay`'s code (cf. option 1).
That was the point of my question regarding performances: if the performances are good enough for you, then there's no strong reason to handle the dirty rectangle cases.
And if they are not good enough, that means we have another problem, because refreshing the screen every half second shouldn't be an issue. That would mean there are `Overlay`s whose drawing takes too much time.
My question: are the performances good enough?

**Comment by mikebravoyes** [comment]
@monsieurtanuki 
Yes, the performance is definitely good enough.

Which is surprising, because I don't handle overlays very economically. Sometimes, there are several hundred overlays on the map. There are approximately 14 different types, but some of them (marker, text, circle) have some dozens of instances. And all of them are re-drawn with every invalidate().

So we can consider this issue as closed. Thank you very much for your elaborate support.

**Comment by mikebravoyes** [comment]
@monsieurtanuki 
Btw: Did you receive the mails I sent to 
"monsieurtanuki \<notifications@github.com\>"?

**Comment by monsieurtanuki** [comment]
@mikebravoyes If you take a look at what happens during a double-click - which provokes a zoom in - you'd be surprised by the number of draws there are. Same when panning the map. The trick is to optimize the display of each `Overlay`.
I did not receive any direct mail from you; I only received mails about this issue.

**Comment by mikebravoyes** [comment]
OK, then I send you here my modified version of MyCompassOverlay, which I used for testing. The following modifications have been applied:

- line 93: default value of mAzimuthPrecision = 0.1 degree (Just a suggestion, to reduce the number of redundant calls.)

- lines 184-200: modified calculation with mScale (Probably irrelevant, as you said the "dirty rectangle" is not used any more. But then, the whole calculation is redundant.)

- line 354: compare operator has to be changed from "<=" to ">="

[MyCompassOverlay.zip](https://github.com/osmdroid/osmdroid/files/4272155/MyCompassOverlay.zip)

**Comment by monsieurtanuki** [comment]
@mikebravoyes Thanks for your tests and code fixes. I kept the azimuth precision to 0 by default though, in order to keep it the way it was.
