### ISSUE TITLE
Android 10 map doesn't load

### ISSUE THREAD

**Issue by F3FFO** [osmdroid/osmdroid#1512]
# Issue Type

[ ] Question
[X] Bug
[X] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

Map doesn't load in android 10, but only in android 9.0 and previous version

### If it's a bug, version(s) of android this affects:

Android 10.0

### Version of osmdroid the issue relates to:

6.1.5

**Comment by spyhunter99** [comment]
i just updated to 10, sample app works fine with gps over here.

**Comment by F3FFO** [comment]
Ah ok ok, i have to download the source and not to implement in gradle is it true?

**Comment by Conan42** [comment]
Hello, I confirm Osmdroid 6.1.5 does not load maps on Android 10. Why?

**Comment by Conan42** [comment]
I just put osmdroid 6.1.6, it has refreshed gradle and its walk thank you spyhunter99

**Comment by cbalster** [comment]
Without further investigating: One possible reason could be the scoped storage changes in API29. The code to determine cache locations seems a little outdated.
https://developer.android.com/about/versions/10/privacy/changes#scoped-storage
That said the sample app works just fine on an API29 emulator, so this is definitely something device specific.

**Comment by mat-sienczyk** [comment]
Version 6.1.6 also does not work on Andorid 10 - app is targeting API 29 (some SQL exceptions). On Android 8 is fine.

**Comment by cbalster** [comment]
I found the Issue.
If you're targeting API29, then the path returned by Environment.getExternalStorageDirectory() is no longer accessible (see [here](https://developer.android.com/reference/android/os/Environment.html#getExternalStorageDirectory)). Same is true for similar methods.
Since the default way of finding a cache directory as implemented in `DefaultConfigurationProvider` does not have access to a `Context`, there is currently no way to get a cache directory on API29 automatically.
The short-term solution is to explicitly set the cache directory before initializing your `MapView`. An Example might look like this:
```
IConfigurationProvider configuration = Configuration.getInstance();
File path = context.getFilesDir();
File osmdroidBasePath = new File(path, "osmdroid");
osmdroidBasePath.mkdirs();
File osmdroidTilePath = new File(osmdroidBasePath, "tiles");
noinspection ResultOfMethodCallIgnored
osmdroidTilePath.mkdirs();
configuration.setOsmdroidBasePath(osmdroidBasePath);
configuration.setOsmdroidTileCache(osmdroidTileCache);
```

@spyhunter99 I already started to clean up the code in `StorageUtils` quite a bit and will update it for newer Android versions. I will do a PR in the next few days.

**Comment by mat-sienczyk** [comment]
@cbalster thanks foe that workaround, here's my implementation in Kotlin (inside Fragment):

`Configuration.getInstance().apply {
            userAgentValue = BuildConfig.APPLICATION_ID
            // workaround for API 29
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                osmdroidBasePath = File(requireContext().filesDir, "osmdroid").apply {
                    mkdirs()
                }
                osmdroidTileCache = File(osmdroidBasePath, "tiles").apply {
                    mkdirs()
                }
            }
        }`

**Comment by unsurv** [comment]
Opting out of scoped storage "temporarily" as described [here](https://developer.android.com/training/data-storage/compatibility) is another possibility that worked for me.

**Comment by monsieurtanuki** [comment]
Fixed by @cbalster's #1571, by @unsurv's [workaround](https://developer.android.com/training/data-storage/compatibility#opt-out-scoped-storage) or by @mat-sienczyk's [workaround](https://github.com/osmdroid/osmdroid/issues/1512#issuecomment-617641607).

**Comment by cbalster** [comment]
> Opting out of scoped storage temporarily as described [here](https://developer.android.com/training/data-storage/compatibility) is another possibility that worked for me.

👍
This will also continue to work with the fix just merged, since it falls back to pre-29 behaviour if no context is supplied.

**Comment by behnamKhan70** [comment]
Add request legacy external storage="true" in manifest.xml

**Comment by vincent-paing** [comment]
This cannot be override on Android 11+. Has this issue been fixed for this case?

**Comment by taiffu** [comment]
"**Add requestlegacyexternalstorage="true" in manifest.xml** is ingnored in Andorid +11 version.

**Comment by monsieurtanuki** [comment]
> Fixed by @cbalster's #1571, by @unsurv's [workaround](https://developer.android.com/training/data-storage/compatibility#opt-out-scoped-storage) or by @mat-sienczyk's [workaround](https://github.com/osmdroid/osmdroid/issues/1512#issuecomment-617641607).

@taiffu None of those solutions work in 30+ ?

**Comment by taiffu** [comment]
Yep those are not work in Android +30 . From Google given guide https://support.google.com/googleplay/android-developer/answer/10467955. I think this may is showstoper for many apps who uses osmdroid in production. We need solution before 5.5.2021 for our app also because all other file permission are soved execept this map cache issue.  I think this also related to issue with sharedpreferences and exist when user updated device to Android 11.  

Osmdroid cache location becomes not readable on upgrade to Android 11
 https://github.com/osmdroid/osmdroid/issues/1678

**Comment by monsieurtanuki** [comment]
What if we stored the tiles in the app specific folder instead? Beyond the historical reasons behind a common `osmdroid` folder.

**Comment by taiffu** [comment]
I think that may solution for this and  also that sharedpreference issue need check in cases where user device is updated to +30 Android.

**Comment by monsieurtanuki** [comment]
For the record, I've just run a small test on an app not related to osmdroid where I copied parts of the code:
1. I get the computed folder ( `getBestWritableStorage(final Context context)`)
2. I create it if it does not exist
3. I create a text file in this folder, with data
4. I read the data
5. all this happened in `onStart`

I've run the test 3 times, on an Android 30 emulator:
```
computed folder is /data/user/0/com.mytestapp/files/osmdroid
text file does not exist
text file written to
text file does exist
text file read from
...
computed folder is /data/user/0/com.mytestapp/files/osmdroid
text file does exist
text file read from
...
computed folder is /storage/emulated/0/Android/data/com.mytestapp/files/osmdroid
text file does not exist
text file written to
text file does exist
text file read from
```

Funny thing is that the computed folder is not always the same (I don't store the path in the preferences). Could be because we're looking for the folder with the largest available storage.
From additional logs, I know that those were the only 2 suggested folders.

Part of the problem seems to be that once a folder is considered the best, the path is stored in the preferences and will be reused, regardless of the fact that this path may be inaccessible in the future - like when Android changes the security.

My suggestion: if API >= 30, set manually the folders to app related subfolders.
I know, it means that you cannot reuse all the tile data from the common `osmdroid` folder.

**Comment by Poras31** [comment]
why open street map is not working on android 10
