### ISSUE TITLE
as start 6.1.6 error

### ISSUE THREAD

**Issue by itsgm** [osmdroid/osmdroid#1515]
* What went wrong:
A problem occurred evaluating root project 'osmdroid-parent'.
> Could not get resource 'https://raw.githubusercontent.com/gradle-fury/gradle-fury/v1.1.4/gradle/maven-support.gradle'.
   > Could not GET 'https://raw.githubusercontent.com/gradle-fury/gradle-fury/v1.1.4/gradle/maven-support.gradle'.
      > Connection reset

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

CONFIGURE FAILED in 3s
Connection reset
Open File

**Comment by spyhunter99** [comment]
if you are building osmdroid from source, you'll have to be online. Both of those links load just fine for me. If you really really want to,  you can download the scripts, put them into the gradle folder, then update all the build files to point to that relative location instead of the github link. But this would be silly.

but since you are using the release version, i'm guessing you are one of those people that "import" source code from another repo into your own project. This is silly. Not sure why people do this or who promotes it but it should stop. You can always do a separate checkout if you need the source for whatever reason.

we publish the artifacts and source code jars to central and tools like intellij and android studio do a pretty good job of resolving the source jars and/or decompiling the aar to give you an equivalent source.

So what exactly are you trying to do?

**Comment by spyhunter99** [comment]
not an issue anymore
