### ISSUE TITLE
Failed to resolve: org.osmdroid:osmdroid-third-party:6.1.6

### ISSUE THREAD

**Issue by aamir-github** [osmdroid/osmdroid#1562]
## Issue Type
Bug

## Description and/or steps/code to reproduce the problem

I have created a sample project for showing the map by using osmdroid library [tutorial ](https://github.com/osmdroid/osmdroid/wiki/How-to-use-the-osmdroid-library)and the [link](https://github.com/osmdroid/osmdroid/wiki/How-to-add-the-osmdroid-library-via-Gradle). Things work fine except the dependency "org.osmdroid:osmdroid-third-party:6.1.6". On adding this dependency the error appears,
Failed to resolve: org.osmdroid:osmdroid-third-party:6.1.6

## Environment
Android Studio (Gradle)

### If it's a bug, version(s) of android this affects:
Android studio: 3.5.2

### Version of osmdroid the issue relates to:
6.1.6

**Comment by spyhunter99** [comment]
The last build with it included 6.0.1. It was deprecated mostly because no one was maintaining it. Also google maps has changed so significantly that it was difficult to maintain api compatibility. So we, collectively just decided to do our own thing. Looking at the commit history, it was definitely me and i failed to make a ticket for it, sorry. I'll update the wiki

**Comment by spyhunter99** [comment]
updated, hopeful this clears things up a bit
