### ISSUE TITLE
Offline map in Android Wear using Mapforge - Very slow rendering of tiles when zoom is changed

### ISSUE THREAD

**Issue by prantoran** [osmdroid/osmdroid#1588]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

Issue Type
[ ] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[*] Performance
[ ] Documentation

Description and/or steps/code to reproduce the problem
I developed an offline map android application using osmdroid and installed it on the watch. I placed the .map file in /sdcard/osmdroid/. I included the required permissions in the manifest file. I have not tried sqllite for offline maps and I have not found out how to do it for .map mapforge files.

Environment
The smartwatch device I am using is LG G Watch R and the operating system is Lenok. It has 4 ARMv7 Processors. I think it has 512MB ram.

The offline maps loads but they are very slow compared to online maps.

If it's a bug, version(s) of android this affects:
All

Version of osmdroid the issue relates to:
6.1.2

**Comment by monsieurtanuki** [comment]
@prantoran I'm not an expert in MapsForge, but as your device has low memory (512Mb) I suspect the problem is that the "unpacking" of your offline map file is very demanding, CPU-wise and memory wise.

My suggestions:
1. Test what happens if you use a small offline map file - is that faster?
1. Don't be demanding on memory - if you're using `MapTileProviderBasic` clear the [performance vs. memory parameters](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/MapTileProviderBasic.java#L114) like `getTileCache().getProtectedTileComputers()`

**Comment by prantoran** [comment]
Thank you for your reply. Yes, it is faster when I use a small offline map. I guess it is due to resource issues.
