### ISSUE TITLE
Invalidate map after adding Waymarked Trails

### ISSUE THREAD

**Issue by applikationsprogramvara** [osmdroid/osmdroid#1648]
I'm trying to add `Waymarked Trails Hiking` from web-site https://hiking.waymarkedtrails.org/ as an overlay.

My issue is: the overlay does not appear on the map immediately. 
How to display it correctly?

Here is the code I constructed based on examples from stackoverflow:
``` java
MapTileProviderBase provider = new MapTileProviderBasic(this);
provider.setTileSource(new XYTileSource(
    "WayMarkedTrails Hiking", 0, 18, 256, ".png",
    new String[] { "https://tile.waymarkedtrails.org/hiking/" }));
TilesOverlay overlay = new TilesOverlay(provider, this);
overlay.setLoadingBackgroundColor(Color.TRANSPARENT);
mapView.getOverlays().add(overlay);
mapView.invalidate();
```
I'm using OSMDroid version is 6.1.6.
I tried on different Android versions from 5 to 10.

* The overlay is added by click on a button.
* On button click nothing happens. The previous underlying map is still visible.
* On map drag or zoom the overlay appears and displayed correctly
* I made an extra button for mapView.invalidate() and on click the overlay is also displayed

I had an idea, that the overlay is actually loading in background, but is not drawn after loading. So after some experiments and adding this code the overlay is displayed.

```java
new Handler(Looper.getMainLooper()).postDelayed(() -> {
        mapView.postInvalidate();
    }, 50);
```

So here is my question: How to display the overlay correctly and after click on a button?

**Comment by monsieurtanuki** [comment]
@applikationsprogramvara It looks familiar. I guess you already had a look at [`SampleWithTilesOverlay.java`](https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/samples/SampleWithTilesOverlay.java).
You're right: it's about `invalidate`ing the map view.
Could you have a look at #690?

> We have async tile downloads, and a MapView.
How do new tiles refresh the MapView: only because whenever a tile is successfully downloaded, it calls (by default) a Handler of class SimpleInvalidationHandler, that explicitly calls MapView.invalidate.
Another way to refresh the MapView is to move/pinch the map.
And the problem so far with the secondary tile provider is that you have to explicitly tell your provider how to behave when a tile is successfully downloaded. If not you just ask it to download tiles into the cache, regardless of the display. And you don't have to do it explicitly for the primary tile provider because it's done in MapView.setTileProvider.
Therefore you should add something like
`anotherTileProvider.setTileRequestCompleteHandler(mMapView.getTileRequestCompleteHandler());`

**Comment by applikationsprogramvara** [comment]
Thank you for your feedback!

After adding the line, the overlay is displayed correctly on the map:
``` java
provider.getTileRequestCompleteHandlers().add(mapView.getTileRequestCompleteHandler());
```
_Note: It appeared that `setTileRequestCompleteHandler` is deprecated._
