### ISSUE TITLE
Failed to resolve: org.osmdroid:osmdroid-android:4.4

### ISSUE THREAD

**Issue by xiaoyanqiang** [osmdroid/osmdroid#168]
I add the osmdroid library via gradle, but encounter this problem: 
Failed to resolve: org.osmdroid:osmdroid-android:4.4

I try the 4.3, it works well.

**Comment by spyhunter99** [comment]
build with maven first

**Comment by lucas-coelho** [comment]
I'm having the same problem. I try to use maven but still with the same problem.

**Comment by lucas-coelho** [comment]
The problem is that the version 4.4 is not publish in jcenter.

**Comment by spyhunter99** [comment]
that's because it hasn't been released. 4.3 is the release version. The current development branch 'master' is on version 4.4-SNAPSHOT. The snapshot version hasn't been published to nexus because it's not a release version. If you want to live on the edge and use the current development branch, check it out (git clone....), build the project with maven (maven clean install)

then from your app, (assuming gradle), use the mavenLocal repository and use compile org.osmdroid:osmdroid-android:4.4-SNAPSHOT@aar
