### ISSUE TITLE
Location overlay is destroyed on screen rotation

### ISSUE THREAD

**Issue by Taknok** [osmdroid/osmdroid#1680]
## Issue Type

[ ] Question
[X] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
When the device is switch to landscape, the location overlay is destroyed and recreate. It does not for markers. It can be reproduced with the demo app (openstreetmapviewer).
This video shows a correct behaviour for marker which are not destroyed (more samples -> data -> marker):
![ezgif com-optimize(1)](https://user-images.githubusercontent.com/12498020/104844953-324a3580-58d3-11eb-919a-602d8ad973c6.gif)

This video shows the location overlay with a timer to change the icon. On screen rotation the location disappear, repop at when get a new fix (onlocation). Exemple with more samples -> location -> Directed location overlay
![ezgif com-optimize](https://user-images.githubusercontent.com/12498020/104844938-1f376580-58d3-11eb-87d4-36d45a55ee86.gif)

This behavior is also present with MyLocationNewOverlay.

## Environment
Tested on Android 10 and 11

### Version of osmdroid the issue relates to:

6.1.1 and above (not tested for other versions)

**Comment by monsieurtanuki** [comment]
@Taknok I think you actually describe the way Android works: when the screen is rotated, the activity is destroyed and another one is created from scratch.
The general problem with Android dev is to make data persistent, so that they don't disappear because of a screen rotation or a phone call.
In the demo "that works", new Markers with the same hard-coded characteristics are created for each new Activity.
You can make data persistent with SQLite ou SharedPreferences, for instance.
I guess you can find tons of literature about that on the web.

**Comment by Taknok** [comment]
Ho ok, I thought the Configuration object was handling this type of scenario (by serializing overlays and recreating them).
