### ISSUE TITLE
Are animated markers supported?

### ISSUE THREAD

**Issue by chitgoks** [osmdroid/osmdroid#1685]
i wish to place a marker with an effect in any way similiar to this

[https://i.stack.imgur.com/DAFED.gif](https://i.stack.imgur.com/DAFED.gifl)

**Comment by chitgoks** [comment]
ok thank for the top. ill close this. only wanted verification.

**Comment by chitgoks** [comment]
@monsieurtanuki  just wondering if you have any idea if this still works in osmdroid?

https://github.com/osmdroid/osmdroid/issues/653

**Comment by monsieurtanuki** [comment]
@chitgoks I guess you can try it with the sample osmdroid app named "Animated Marker".
But from what I read in the code, the `Marker` is called "animated" because the geolocation moves, not because the logo itself evolves.
That being said, you can find inspiration there for the timer (that triggers a frequent display refresh) and the circles drawn for the location accuracy (that look like your GIF).
