### ISSUE TITLE
IMapController.setCenter() gravely inaccurate (not 100% reproducible)

### ISSUE THREAD

**Issue by waltersamson** [osmdroid/osmdroid#1719]
## Issue Type
[x] Question

## Environment:
org.osmdroid:osmdroid-android:6.1.10

## Description:
IMapController.setCenter() inaccurate by a large amount. Sometimes, by swapping setZoom() and setCenter(), it'll center on the correct location, sometimes it won't.

## Steps to reproduce:
Follow the guide (https://github.com/osmdroid/osmdroid/wiki/How-to-use-the-osmdroid-library-(Java))
Use the following code in MainActivity:
```
package com.example.osmdroidtest;

public class MainActivity extends AppCompatActivity {
    private MapView map;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        Context ctx = getApplicationContext();
        Configuration.getInstance().load(ctx, PreferenceManager.getDefaultSharedPreferences(ctx));

        setContentView(R.layout.activity_main);

        map = (MapView) findViewById(R.id.map);
        map.setTileSource(TileSourceFactory.MAPNIK);

        Handler hdlr = new Handler(Looper.myLooper());
        hdlr.postDelayed(new Runnable() {
            @Override
            public void run() {
                map.getController().setCenter(new GeoPoint(35.551503, 139.788436));
                map.getController().setZoom(15.0);
            }
        }, 10000);
    }
}
```
Note that to prevent operations on the map before 100% initialization, setCenter() and setZoom() is delayed by 10 seconds.

## Expected result:
Map should center on GeoPoint(35.551503, 139.788436), which is in Tokyo Haneda airport.

## Actual result:
Maps centers over 100km to the northwest of Tokyo.

## More details
Once it shows this faulty behaviour, after arranging setCenter() after setZoom() it'll most likely work correctly. 

However, once it works correctly, swapping the two statements back doesn't make it behave faulty again, and we can use whatever order between setCenter() and setZoom(). 

But maybe after some time it'll suddenly revert to the faulty behaviour, and we have to use setCenter() after setZoom() again.

**Comment by monsieurtanuki** [comment]
@waltersamson You should set the zoom level first, then the center.
Once the zoom is correct, the geo point can be correctly projected into the map.
If you set the center first and then set the zoom to a much bigger value, you'll lose precision because setting the center computed a projected pixel that will be potentially wrongly extrapolated into a bigger map with a bigger zoom. We don't keep the geo point value, we just say "at this time, we set the center of the map for the current zoom level".
But if you set the center first and then set the zoom to a much lower value, there won't be any precision problem.

**Comment by waltersamson** [comment]
Thanks for the detailed info! I'll experiement more with the settings.
