### ISSUE TITLE
Issue with Markers resolution

### ISSUE THREAD

**Issue by MKergall** [osmdroid/osmdroid#1738]
I'm completely stucked with a strange issue related to Markers resolution on high-density screens. 
I define my Marker icons with only 1 resolution, in res/drawable-mdpi directory. 

On one application (OSMNavigator), Marker icons are automatically resized according to the screen density - as needed and expected. 

On another application (NooTous), this doesn't work at all: Marker icons are not resized. 

Same version of osmdroid (6.1.11). Same target SDK (30). Same test device (API 30, 420 dpi). 
The only difference I can see is that the first app is based on old-style Activity model, while the second app is based on Fragment. 

(both applications here: https://github.com/MKergall/osmbonuspack)

## Issue Type

[ X ] Question

**Comment by monsieurtanuki** [comment]
It wouldn't be the first time that Android messes up with drawable expected behaviors; there are already a couple of related issues.
My suggestion: just populate the 5 dpi drawable folders. If that does not work, that's another story.

**Comment by MKergall** [comment]
@monsieurtanuki I also used this workaround. My real problem is that I have the same issue with icons downloaded from Internet (typically: icons referenced in KML files). And for those icons, no way to handle multiple resolutions. 

(Could you point me to related issues?)

**Comment by monsieurtanuki** [comment]
@MKergall I don't know if this problem is caused by the Android version (30+) or the code.

It could be interesting to have a look at an optimization I coded in [`Marker.drawAt`](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/overlay/Marker.java#L574-L590), that I would sum up as: `canvas.drawBitmap( mIcon...)` or `mIcon.draw(pCanvas)`.
Could you test if one of them works in your KML case?
Then, it would make sense to be able to force the choice of the good solution - for the moment it's coded as `if (mIcon instanceof BitmapDrawable)`.
And probably being able to say: I want this Marker's icon to be displayed as big as possible in a specified [width, height] rectangle (cf. `final int markerWidth = mIcon.getIntrinsicWidth()`) is a path to the solution.

**Comment by MKergall** [comment]
All my icons are BitmapDrawables. 
I will try to test the other case: mIcon.draw(pCanvas) - I will have to subclass the Marker. 

Something even stranger: I tried with another test device: API 27, 420 dpi => 
- Marker based on a resource drawable-mdpi is correctly resized (!!!). 
- KML Marker (icon downloaded at runtime) is still not resized. 

Using `bitmap.setDensity(DisplayMetrics.DENSITY_MEDIUM);` has absolutely no effect.

**Comment by monsieurtanuki** [comment]
Probably you'll have more control over the display size with the second syntax, with `mIcon.setBounds(mRect)` then `mIcon.draw(pCanvas)`.

**Comment by MKergall** [comment]
Yes!!!! 
@monsieurtanuki, you pointed directly to the right place :
I removed the "mIcon instanceof BitmapDrawable/pCanvas.drawBitmap" option, and forced "mIcon.draw(pCanvas);" way. 
=> Marker icons now have the correct size, in all configurations: 
- mdpi resources, 
- downloaded at runtime - as long as I set their density: bitmap.setDensity(DisplayMetrics.DENSITY_MEDIUM);

In addition, the colouring of KML icons (a standard KML feature implemented in OBP), which had also disapeared, is back to normal. 

![image](https://user-images.githubusercontent.com/1849606/132735806-81a2f30d-bc1f-47ed-8d8f-1141373e7217.png)

**Comment by monsieurtanuki** [comment]
@MKergall Wonderful!
If you can confirm with additional tests, I suggest that you create a PR that removes the "optimized for BitmapDrawable" option that is 15% faster but not 100% supported...
