### ISSUE TITLE
Import shp file got java.lang.IllegalArgumentException: north must be in [-85.05112877980658,85.05112877980658]

### ISSUE THREAD

**Issue by wogno** [osmdroid/osmdroid#1751]
Please note: issues related to or caused by osmbonuspack will be closed with a
suggestion to open an issue at https://github.com/MKergall/osmbonuspack

(feel free to delete whatever doesn't apply)

## Issue Type

[ ] Question
[x ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem
I loaded polygon from shape(.shp) files
![image](https://user-images.githubusercontent.com/31076843/142773057-d47c30ef-2975-4c78-8619-d078a87d7294.png)

## Environment
Android Studio on Windows and real phone(Infinix Note 6) for simulation

### If it's a bug, version(s) of android this affects:

All

### Version of osmdroid the issue relates to:

6.1.11

**Comment by eclectice** [comment]
I notice this non-fatal IllegalArgumentException only when the Mapnik database where at its extreme zoom level (global view)

**Comment by monsieurtanuki** [comment]
@wogno What I can say is:
* there's probably some latitude that is too high in your data
* the range for latitude with the default projection on osmdroid is +-85.05112877980658 (cf. https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/util/TileSystemWebMercator.java#L9-L10)
* in shape converter we truncate latitude so they can fit, but unfortunately we are too generous and min/max latitudes are +-90 (cf. https://github.com/osmdroid/osmdroid/blob/master/osmdroid-shape/src/main/java/org/osmdroid/shape/ShapeConverter.java#L187-L202)
* if in shape converter we truncated latitudes to +-85.05112877980658 we should probably be OK

Does that make sense?

@eclectice I think your issue is slightly different: ok it's still a problem of latitudes, but in your case it's about "multi-world" side-effects.

**Comment by spyhunter99** [comment]
should be fixed in the next release
