### ISSUE TITLE
[Question] Map represented by less tiles

### ISSUE THREAD

**Issue by Rafal-Okuniewski** [osmdroid/osmdroid#1753]
## Issue Type

[X ] Question
[ ] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description
Hi. I have a need to lay out the tiles in a different way. I want the tile to take up more space than before. For example:
![image](https://user-images.githubusercontent.com/44557039/144406877-dc41818e-ce21-4c55-8969-682c7fa5f49d.png)

I use a custom class OnlineTileSourceBase which provides tiles. I would simply like for example, the whole map to be represented by 4 or 1 tile. What is the solution for this?

**Comment by monsieurtanuki** [comment]
Hi @Rafal-Okuniewski!
I'm not sure if that solves your issue, but you might find that method in `MapView` interesting:
```java
/**
 * Setting an additional scale factor both for ScaledToDpi and standard size
 * > 1.0 enlarges map display, < 1.0 shrinks map display
 *
 * @since 6.1.0
 */
public void setTilesScaleFactor(float pTilesScaleFactor) {
    mTilesScaleFactor = pTilesScaleFactor;
    updateTileSizeForDensity(getTileProvider().getTileSource());
}
```

**Comment by Rafal-Okuniewski** [comment]
@monsieurtanuki 
Thank you very much for your quick reply and suggestions. I've tested this setting and it kind of zooms the map out so of course there are fewer tiles but it gives the impression of unnecessary zooming in on the map, and I'd just like one tile to be able to fill the whole area without the zoom.

**Comment by monsieurtanuki** [comment]
> I'd just like one tile to be able to fill the whole area without the zoom

It's not possible. In osmdroid we basically use 256x256 PNG/JPEG tiles, that we display next to each other in order to display a map. If you want one tile to fill the whole area without the zoom, you need to find a tile provider with bigger tiles (e.g. 512x512). Or a smaller screen ;)
I still don't really understand the reason behind "one tile fills all the space"...

**Comment by Rafal-Okuniewski** [comment]
@monsieurtanuki 
I have a server which I can query for tiles of a suitable resolution e.g. 515 x 512, 1024 x 1024 and I want to place them on the map. When I ask for a better resolution it does not make the tile take up more space, it is just in better quality.
My OnlineTileSourceBase download class , any suggestions?

`public class CustomWMSTileSource extends OnlineTileSourceBase {

    private static final String MAP_SRS = "EPSG:4326";

    private final MapLayerView mapLayerView;

    public CustomWMSTileSource(@NonNull MapLayerView mapLayerView) {
        super(mapLayerView.getLayerRequestSettings().getLayers(), mapLayerView.getMinZoom(),
                mapLayerView.getMaxZoom(), 1024, "png",
                new String[]{mapLayerView.getLayerRequestSettings().getUrl()});
        this.mapLayerView = mapLayerView;
    }

    @Override
    public String getTileURLString(final long pMapTileIndex) {

        StringBuilder stringBuilder = new StringBuilder(getBaseUrl())
                .append("?request=").append("GetMap")
                .append("&width=").append(getTileSizePixels())
                .append("&height=").append(getTileSizePixels())
                .append("&version=").append(mapLayerView.getLayerRequestSettings().getVersion())
                .append("&styles").append(mapLayerView.getLayerRequestSettings().getStyles())
                .append("&layers=").append(mapLayerView.getLayerRequestSettings().getLayers())
                .append("&service=").append(mapLayerView.getLayerRequestSettings().getService())
                .append("&bbox=");

        int x = MapTileIndex.getX(pMapTileIndex);
        int y = MapTileIndex.getY(pMapTileIndex);
        int z = MapTileIndex.getZoom(pMapTileIndex);

        BoundingBox boundingBox = tileToBoundingBox(x, y, z);

        stringBuilder
                .append(boundingBox.getLonWest()).append(",")
                .append(boundingBox.getLatSouth()).append(",")
                .append(boundingBox.getLonEast()).append(",")
                .append(boundingBox.getLatNorth());

        stringBuilder
                .append("&srs=").append(MAP_SRS)
                .append("&format=").append(mapLayerView.getLayerRequestSettings().getFormat())
                .append("&transparent=").append(mapLayerView.getLayerRequestSettings().isTransparent());

        if (!TextUtils.isEmpty(mapLayerView.getLayerRequestSettings().getMap())) {
            stringBuilder.append("&map=").append(mapLayerView.getLayerRequestSettings().getMap());
        }

        if (BuildConfig.DEBUG) {
            Timber.i(stringBuilder.toString());
        }

        return stringBuilder.toString();
    }

    private static double tileToLongitude(int x, int z) {
        return x / Math.pow(2.0, z) * 360.0 - 180;
    }

    private static double tileToLatitude(int y, int z) {
        double n = Math.PI - (2.0 * Math.PI * y) / Math.pow(2.0, z);
        return Math.toDegrees(Math.atan(Math.sinh(n)));
    }

    private static BoundingBox tileToBoundingBox(final int x, final int y, final int zoom) {
        return new BoundingBox(
                tileToLatitude(y, zoom),
                tileToLongitude(x + 1, zoom),
                tileToLatitude(y + 1, zoom),
                tileToLongitude(x, zoom)
        );
    }

}`

**Comment by Rafal-Okuniewski** [comment]
@monsieurtanuki Hm... so here is an example because I am not sure if I understand correctly. If I use z/x/y instead of my provider when I ask a server for default 256x256 tiles then on a device with 1920x1080 resolution 32(8x4) tiles will be visible, and if I ask for 512x512 tiles the screen will show 8(4x2) tiles without zoom - same visible area.

**Comment by monsieurtanuki** [comment]
Hi @Rafal-Okuniewski!
1. regardless of the tile provider (z/x/y or not) the behavior is basically the same - it's just that there are possible side effects if you have to convert your tiles in order to fit into z/x/y
2. 1920 / 256 = 7.5 and 1080 / 256 = 4.22, therefore in first approach you'll see approximately 7.5 x 4.22 tiles (similar to your 8 x 4)
3. 1920 / 512 = 3.75 and 1080 / 512 = 2.11, therefore in first approach you'll see approximately 3.75 x 2.11 tiles (similar to your 4 x 2)
4. that being said, you should take into account the dpi - I think that in osmdroid it's taken into account automatically in order to match your smartphone display (but that can be turned off)
5. it's not going to be the same area, because your 512x512 tile and your 256x256 tile reflect the same z/x/y - you'll see 2x2=4 times less geo area with 512x512
6. it's not going to be more accurate with 512x512, it's probably the same display on 512x512 with z/x/y compared to 256x256 with z+1/x/y
7. be careful that in osmdroid we use zoom as `double` (and not `int`) - if you use zoom 13.999 it will look like clear zoom 13 but stretched almost twice, and if you use zoom 14 it's going to be very clear - you can switch that off and only use `int` zooms

**Comment by Rafal-Okuniewski** [comment]
@monsieurtanuki 
I achieved what I wanted when I changed the size of the tiles for the map source, that is when I modified the tile size for the source from 256 to 512 then this also made the tiles in the layers also take up a larger area of 512 pixels.  Thank you for your time and guidance, I really appreciate it.

**Comment by monsieurtanuki** [comment]
You're welcome @Rafal-Okuniewski!
