### ISSUE TITLE
how to remove the last point in a polyline

### ISSUE THREAD

**Issue by jayhuang861019** [osmdroid/osmdroid#1887]
i want to remove the last point of a polyline,i try like this
```
   public void removeLastPoint() {
        int size = getActualPoints().size();
        if (size <= 1) return;
        getActualPoints().remove(size - 1);
    }
```
but it does not work ,the polyline on the map still has the last point,but when i add a new point to the polyline,the polyline be refreshed,and the point I deleted earlier is no longer there, and the new point has been added
so What is the right way to remove the last point?

**Comment by jayhuang861019** [comment]
but remove the last point of a polyline is a common requirement
Actually I implemented this function through the following code
```
 int size = getActualPoints().size();
        if (size <= 0) return false;
        getActualPoints().remove(size - 1);
        setPoints(new ArrayList<>(getActualPoints()));
```
am i right?

**Comment by monsieurtanuki** [comment]
> but remove the last point of a polyline is a common requirement

I don't remember any previous issue about it, but don't hesitate to send a PR.

> Actually I implemented this function through the following code
> [...]
> am i right?

I would say no, as `Warning: changes on this list may cause strange results on the display.`.
I would suggest you to keep the list of the geo points in a variable, add points and remove points to it, and then use `setPoints`. Instead of changing `getActualPoints()`.

**Comment by jayhuang861019** [comment]
ok thank u
