### ISSUE TITLE
crack

### ISSUE THREAD

**Issue by vitg8** [osmdroid/osmdroid#1918]
взломали карты , город ростов вместо надписей в некоторых местах написаны оскорбления Россиян ,примите пожалуйста меры

**Comment by Vasilisk7** [comment]
Такая же проблема и в других городах России!

**Comment by panovvitalik** [comment]
Такая же проблема Москва. Причем в браузере - те же

**Comment by panovvitalik** [comment]
The project is deied?

**Comment by spyhunter99** [comment]
i have no idea what's going on here. looks like this application is using the map tile source called OpenStreetMaps. This library does NOT provide map data, it only displays it. Whatever it is you all are complaining about most likely isn't the library but the map source you're using

**Comment by panovvitalik** [comment]
https://community.openstreetmap.org/t/topic/102894

https://community.openstreetmap.org/t/vandalism-report/102714

**Comment by panovvitalik** [comment]
The issue is not solved!

**Comment by spyhunter99** [comment]
Well you can try clearing the map tile cache, maybe that's the issue. Otherwise it's not an osmdroid issue

**Comment by eclectice** [comment]
The area close to the Myakininskiy Subway Bridge (кининcки метромоcт) appears to load perfectly in my app, which uses the OsmDroid library. I should mention that I'm using the standard MAPNIK tile source. 

It appears that your app's view rendering is flawed because a grey box is overlaid over the plus button. 
The fact that the grey boxes don't have uniform sizes to represent them as typical map tiles is another piece of supporting evidence. If these grey boxes are really map tiles, they should appear behind those buttons.

Therefore, I don't think this is a problem with the OpenStreetMap map, the MAPNIK library, or even OsmDroid.

https://www.openstreetmap.org/way/400154667#map=15/55.8330/37.3958

![Screenshot_20230829_100919_BFT-TRC5200](https://github.com/osmdroid/osmdroid/assets/1452656/52dc5f35-3121-4736-b373-d747d1a97589)
