### ISSUE TITLE
New Night Mode in V5.0.1

### ISSUE THREAD

**Issue by hlaurent** [osmdroid/osmdroid#210]
This looks great but I can't find how to implement it.
How do you use this new "rudimentary night mode"?

**Comment by spyhunter99** [comment]
It's in the sample app. i'll add it to the wiki

this.mMapView.getController().setInvertedTiles(true);

**Comment by spyhunter99** [comment]
you can find the sample in the example app via
launch the app > first item on the list > menu > samples, inverted tiles (i think)

**Comment by hlaurent** [comment]
Thanks a lot. It does work as expected.

Henri

**Comment by spyhunter99** [comment]
For those that stumble on this in the future, the API was changed in 5.1 to make it more user extensible. The sample app is also updated too

**Comment by aritrabasu104** [comment]
@spyhunter99 how to use night mode now?
P.S. I am stuck because i cant build sample in Android studio (https://github.com/osmdroid/osmdroid/tree/master/OpenStreetMapViewer)

**Comment by spyhunter99** [comment]
Gradlew build?

On Jul 26, 2017 5:16 AM, "ARITRA BASU" <notifications@github.com> wrote:

@spyhunter99 <https://github.com/spyhunter99> how to use night mode now?
P.S. I am stuck because i cant build sample in Android studio (
https://github.com/osmdroid/osmdroid/tree/master/OpenStreetMapViewer)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/osmdroid/osmdroid/issues/210#issuecomment-317997525>,
or mute the thread

**Comment by spyhunter99** [comment]
It's on they play store as open map, the apk is in the release zip on
github too

**Comment by aritrabasu104** [comment]
But can't I see source code in Android Studio  and make changes as I do can with other applications?

**Comment by spyhunter99** [comment]
Yes that's what I use,  what version ate you using?  Works fine here. What
error do you get?

**Comment by aritrabasu104** [comment]
got it working
