### ISSUE TITLE
compile 'org.osmdroid:osmdroid-android:5.0.1@aar' not working for me

### ISSUE THREAD

**Issue by hgoebl** [osmdroid/osmdroid#217]
I tried `compile 'org.osmdroid:osmdroid-android:5.0.1@aar'`. The effect was, that I found all the stuff in build/intermediates/exploded-aar/org.osmdroid. But the compiler didn't find the classes (like e.g. MapView).

When I tried `compile 'org.osmdroid:osmdroid-android:5.0.1'` instead, it worked.

My configuration:

* used in a library project
* Gradle 2.2.1 (when built via command-line)
* Android Studio 1.5

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.5.0'
    }
}
apply plugin: 'com.android.library'
apply plugin: 'maven'

repositories {
    jcenter()
    mavenCentral()
    mavenLocal()
}

...
```

Note: currently I switched back to 4.1 because of breaking changes in 5.0.
BTW is there some kind of discussion how to migrate from 4.x to 5.0? I've found only few information in the changelog. Can I drop my own implementation of RotationGestureOverlay? What is the impact of ResourceProxy changes?

**Comment by spyhunter99** [comment]
RotationGestureOverlay - I'm not sure what yours does, but there were definitely improvements since 4.3.

ResourceProxy - the only change was to anything that implements ITileSource and access to them. One parameter was removed from the constructors (since it wasn't used anywhere), which was the ResourceProxy.string.

The IArchiveProvider added a few new methods and the factory changed to be more extensible. 

Overall, the impact should be minimal 

As to your build issue... no clue. Can you try a newer version of gradle?

**Comment by hgoebl** [comment]
Full success! :+1: 

After switching to Gradle 2.9 all problems vanished. I could delete my RotationGesture* and use the one of 5.0.1.
Seams like "safe canvas" has gone completely? At least I don't encounter any problems without the old 4.1 settings regarding safe canvas.

Thanks! Good work!
