### ISSUE TITLE
Fix travis ci integration

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#227]

**Comment by ZKjellberg** [comment]
Thanks for implementing this. It is great to have automatic reports for pull requests.

I am a bit confused by having multiple build-tools & android SDK targets, as well as having three mvn clean installs. I think only one build-tool is actually used and now that build-tools-23.0.2 looks to be now be available we could remove 23.0.1. The Android SDK target should only require 23 as that is the targetSdkVersion and using the Android 10 emulator which is not on that list gives the appearance it is unnecessary.

Since we can now use Travis CI, this is wonderful and I assume you worked through different approaches to get it working. If you don't mind, I'd like to try trimming down the config slightly as it is currently about 12 minutes to compile.

Again, thanks for figuring this out.

**Comment by ZKjellberg** [comment]
Reviewing logs, I see the mvn clean install only seems to pass on the third attempt, which explains why you run it three times. I still have issues with mvn clean install failing locally due to **OpenStreetMapTileProviderDirectTest** line 57 ```final FileOutputStream fos = new FileOutputStream(path);``` but I assume this is due to testing on Android 6.0 which could be related to permissions.

**Comment by neilboyd** [comment]
I'm reopening this issue because there's more we to be done with Travis.
The build reports also make me happy :)
I'm not really concerned about how long it takes to run because it's just automatic in the background, but of course any little helps.
I'd like to see a few more emulators, ideally all of these api levels: 8, 10, 15, 18, 21, 22, 23

**Comment by spyhunter99** [comment]
> I am a bit confused by having multiple build-tools & android SDK targets,

doesn't matter. the yml file basically just installs those selected components via tools/android sdk update....blah blah... It doesn't affect the build, it just makes sure that your android sdk components are installed and update to date.

> Android 10 emulator
Per the travis docs, API 10 emulator is installed by default somehow. I tried API 8 on a different branch and ran into issues.

**Comment by spyhunter99** [comment]
API 15 failure when reading a the test png file from storage, but only when bitmap reuse options are provided, omitting that overcomes the error. i'll update again later this afternoon

**Comment by spyhunter99** [comment]
still getting intermittent failures on API 8  devices
junit.framework.AssertionFailedError: Compare config expected:<ARGB_8888> but was:<RGB_565>

**Comment by spyhunter99** [comment]
i also see random command timeouts as well as random 'build failed' yet all of the tests pass. No idea

**Comment by spyhunter99** [comment]
regarding API23. i found this. https://github.com/travis-ci/travis-ci/issues/4763 it just may not be supported

**Comment by spyhunter99** [comment]
everything but api 22 and up is working right now. leaving the ticket open until we can get solution on those items

**Comment by spyhunter99** [comment]
update on this. the sample test has unit tests that makes sure that all fragments load. this test works fine under maven, but with gradle, throws an oom exception.

**Comment by spyhunter99** [comment]
we still have occasional time outs due to the avd in a vm being a bit slow, but i'm content as is. the mapsforge adapter branch #245 adds a number of new targets for both google and non google apis so once that's merged we'll be rocking.
