### ISSUE TITLE
the highest zoom level osmdroid supports

### ISSUE THREAD

**Issue by Pekin2Paris** [osmdroid/osmdroid#230]
I tried to implement very detailed regional map, but I cannot go beyond zoom level 22. Until zoom level 22, it works well, but after that mapView doesn't display anything. Is this a limitation of osmdroid? How can I get higher zoom levels using my own tiles? Thank you

**Comment by spyhunter99** [comment]
That's the current limit unfortunately. There's some work to resolve this
https://github.com/osmdroid/osmdroid/pull/48 however it has a number of
issues that need to be resolved for it can happen.

**Comment by spyhunter99** [comment]
Hang on let me clarify, osmdroid's limit is zoom 22, however rendered content is based off of the tile source. You'll need imagery at that zoom level to be available. I think right now, few services provide zoom levels over 18.

**Comment by Pekin2Paris** [comment]
Thank you spyhunter99 for your replying.

> I think right now, few services provide zoom levels over 18.

Well, I agree for street map zoom level 18 is already quite high. But for a specific area, such as a place of interest, I would like to have more details and I can have my own tile sources. I am not good at programming, but is it possible to modify the osmdroid library somewhere to make zoom level 23 or even 24 work? Thank you.

**Comment by spyhunter99** [comment]
Is it possible? sure but it's no easy task. You'd have to pick up the doubles branch, which is working but needs profiling to ensure there isn't a significant performance impact over the standard osmdroid build. Baring any issues, then increase the maximum zoom size in TileSystem to something reasonable. You'll also have to go through the code and change from integer to longs since at > zoom 22, we'll exceed the maximum value for integers.

And then lots of testing, and of course building your tile set

**Comment by Pekin2Paris** [comment]
Thank you very much @spyhunter99 ! This solved my confusion.
