### ISSUE TITLE
Mapsforge adapter

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#245]
https://github.com/MKergall/osmbonuspack/issues/196

osmbonuspack has an adapter that lets us use mapsforge based map data with osmdroid. It hasn't really been maintained and was based off of someone else's work. this issue is to hopefully track and provide the same functionality here within osmdroid's repo as an additional 3rd party library

**Comment by 2ndGAB** [comment]
Hi spyhunter99,
I have a problem to implement it. I have a dependency on ``org.osmdroid:osmdroid-android:5.0.1@aar`` and when it buils ``MapsForgeTielProvider`` it complains about ``org.osmdroid.tileprovider.modules.SqlTileWriter``.

Is it something not in version 5.0.1?

**Comment by spyhunter99** [comment]
Change it to TileWriter. That should fix it

**Comment by 2ndGAB** [comment]
Perfect, build is ok now. I'm going to try to use map files.

**Comment by 2ndGAB** [comment]
I have some problems rendering maps:
At some zoom level, some tiles are rendered as yellow or grey squares (in fact I have larges areas not well rendered) see http://i.imgur.com/LhNqNLS.png.
Could the problem come from the tile provider? Because I don't have such problem on mapsforge application.
Did you experience such issue?

You made a mistaker in your implementation to be able to render several map files:
In ``MapsForgeTileSource()``, you call ``MultiMapDataStore(MultiMapDataStore.DataPolicy.RETURN_FIRST);`` which is not correct.
You should call ``MultiMapDataStore(MultiMapDataStore.DataPolicy.RETURN_ALL);``.
Maybe a test could be performed to know if we provide one or several map files.

Regards

**Comment by spyhunter99** [comment]
Glad you found issues with it. The yellow tiles are cases were mapsforge failed to render that tile. check logcat for the reason. My interepretation of RETURN_FIRST was that if multiple map files contained the same area, return the first rendering available. Did flipping to RETURN_ALL fix the yellow and gray tiles for you?

**Comment by 2ndGAB** [comment]
Hi spyhunter99
I'll to check what happens about yellow tiles.
Without RETURN_ALL it seems we cannot guarantee that adjacent maps cannot overlap. I don't know why and Mapsforge is not precise on that point:
``https://github.com/mapsforge/mapsforge/blob/master/docs/MapDataStore.md``
That will work if maps are not adjacent.
Anyway, in my case, that doesn't work. You can check it with rhone-alpes.map and auvergne's.map in  ``http://download.mapsforge.org/maps/europe/france/``

So I think it would be better to use RETURN_ALL for multiple map files pass it as parameter maybe.

Anyway that doesn't change anything about the yellow tiles.

**Comment by spyhunter99** [comment]
I just pushed the change for return all. give it a shot

**Comment by 2ndGAB** [comment]
Hi spyhunter99, I don't see any problem on logcat but I only see OSMdroid logs such as:

     I/OsmDroid: rescale tile cache from 10 to 9
     I/OsmDroid: Finished rescale in 14ms

**Comment by 2ndGAB** [comment]
Do you know how to get more infos about mapsforge tiles processing?

**Comment by 2ndGAB** [comment]
I found that the problem was mainly caused by the osmdroid directory.
I removed it and I don't have the yellow tiles anymore.

Anyway, tiles are not rendered correctly for zoom level 10 and below.

Any idea?

**Comment by spyhunter99** [comment]
Renders fine over here, but i'm only using a single tile set. let me replicate your setup and try again

**Comment by spyhunter99** [comment]
i'm noticing that text is clipped at higher altitudes, but i have no problems rendering down to zoom max. Do you have a lat/lon for the location in question?

**Comment by 2ndGAB** [comment]
Yes, for example this location/zoom level always fails for me:
https://imgur.com/QbVbJvo

but is ok for zoom level 11

http://i.imgur.com/ETBSC5s.jpg

**Comment by spyhunter99** [comment]
Can you provide an approximate lat lon?

**Comment by 2ndGAB** [comment]
Sorry, I didn't uploaded the right image. It should have been Toasted. 
And maps are:
http://download.mapsforge.org/maps/europe/france/rhone-alpes.map
and
http://download.mapsforge.org/maps/europe/france/languedoc-roussillon.map

lat:47.0796
lng:4.5827

**Comment by 2ndGAB** [comment]
Hy spyh99,

Did you find something?

For information I tried to use rendertheme-V4 and in this situation, maps rendering is ok for zoom level 9-11 (didn't test for lower values) and dosn't render anything for values 12 and higher.

Regards,

**Comment by spyhunter99** [comment]
at those coordinates, i don't have anything. however a bit further south and west, i get tiles. 46.2, 2.9. will post change

**Comment by 2ndGAB** [comment]
Maybe I made a mistake about the coordinates but as I said you can have a look at the screenshots:

At level 10, youo can see that a part of the map is missing around ESTADIO

https://imgur.com/QbVbJvo

but is ok for zoom level 11

http://i.imgur.com/ETBSC5s.jpg

Here are other screenshots taken using rendertheme-v4.xml

http://imgur.com/a/TrFv4

You can see that tiles are rendered at level 11 and 14 but not at level 12 and 13 !?!

**Comment by spyhunter99** [comment]
not denying that there's a problem....
try deleting or renaming the /sdcard/osmdroid/tiles/ folder
and also try turning on tile debugging. In the example app, there's a few
lines commented out that identify what variables to turn on

**Comment by spyhunter99** [comment]
I bet the issue is the cache. I'm assuming you ran your app at some point
when it was to first available instead of all available map files. Osmdroid
got the result and cached the result therefore it had no reason to request
a new render....

**Comment by 2ndGAB** [comment]
Maybe the reason is the cache but not because of the osmdroid folder's content. At least not only.
Remember that the first time I tested your adapter I got yellow squares and I solved the problem by removing osmdroid folder.  so now, I remove it every time I download a new map.
And the fact that the problem always occurs at specific zoom levels, can give info. I don't know how cache works but it seems that a relationship is not correctly established on zoom level between Mapsforge and osmdroid. Like if osmdroid could find tiles of Mapsforge at specific zoom levels. Strange but just an idea as I don't know how it works.

**Comment by 2ndGAB** [comment]
I think you are right.

Things seem to be a bit better in 5.1 but not completely solved. I was in 5.0.1 but I changed because ``OpenStreetMapTileProviderConstants.DEBUG_TILE_PROVIDERS`` was declared ``final``.

At zoom level 9 and below, I get such screen: http://i.imgur.com/Zvk0BdX.jpg

And the application loops on something like:

01-26 09:48:24.791 7925-7925/com.ndguide.ndguide D/OsmDroid: MapTileProviderArray.getMapTile() requested but not in cache, trying from async providers: /9/264/184
	01-26 09:48:24.791 7925-7925/com.ndguide.ndguide D/OsmDroid: MapTileProviderBase.mapTileRequestFailed(): /9/264/184
	01-26 09:48:24.793 7925-7925/com.ndguide.ndguide D/OsmDroid: MapTileProviderArray.getMapTile() requested but not in cache, trying from async providers: /9/260/185
	01-26 09:48:24.793 7925-7925/com.ndguide.ndguide D/OsmDroid: MapTileProviderBase.mapTileRequestFailed(): /9/260/185
	01-26 09:48:24.793 7925-7925/com.ndguide.ndguide D/OsmDroid: MapTileProviderArray.getMapTile() requested but not in cache, trying from async providers: /9/261/185
	01-26 09:48:24.794 7925-7925/com.ndguide.ndguide D/OsmDroid: MapTileProviderBase.mapTileRequestFailed(): /9/261/185
	01-26 09:48:24.795 7925-7925/com.ndguide.ndguide D/OsmDroid: MapTileProviderArray.getMapTile() requested but not in cache, trying from async providers: /9/262/185
	01-26 09:48:24.795 7925-7925/com.ndguide.ndguide D/OsmDroid: MapTileProviderBase.mapTileRequestFailed(): /9/262/185
	01-26 09:48:24.802 7925-7925/com.ndguide.ndguide D/OsmDroid: MapTileProviderArray.getMapTile() requested but not in cache, trying from async providers: /9/263/185
	01-26 09:48:24.802 7925-7925/com.ndguide.ndguide D/OsmDroid: MapTileProviderBase.mapTileRequestFailed(): /9/263/185


At higher zoom level values, if I start from a clean osmdroid folder, that works fine.

**Comment by rastikw** [comment]
As mentioned in https://github.com/MKergall/osmbonuspack/issues/196 I'm using slightly different mapsforge integration with mapsforge-0.6.0. But I was having the same problems with MultiMapDataStore.
I'm using my own map files that slightly overlap. Depending on the way I zoom into detail it was easy to get tiles rendered from the map.

**Comment by spyhunter99** [comment]
@2ndGAB do you have any problems with using mapsforge directly using their sample app and the same data sets? I'm just having a hard time replicating the problem over here. I'm primarily testing on a samsung s5 (no endorsement implied). I'll see if I can whip up some test cases for this and get travis running the tests on a few different avd's. it's possible that you're running into an android api specific thing or it's an issue with mapsforge. I've seen strange issues with mapsforge on certain devices. Maybe there's debugging options we can turn on for mapsforge to isolate the issue

**Comment by spyhunter99** [comment]
added some additional optional fields and null checks.

**Comment by 2ndGAB** [comment]
always on branch 245?
I've some other problem to solve but I'll check if I have the same problem with mapsforge Samples app.

**Comment by spyhunter99** [comment]
yes on #245

**Comment by 2ndGAB** [comment]
So I made a try with MapsForge Samples Appllication and it work fine.
I don't have any problem at any zoom level.

I just modified MultiMapLowResWorld Activity to load 2 french regional maps.

You can test it on [GitHub] (https://github.com/2ndGAB/Mymapsforge-master), and by downloading [rhone-alpes.map](http://download.mapsforge.org/maps/europe/france/rhone-alpes.map and [provence-alpes-cote-d-azur.map] (http://download.mapsforge.org/maps/europe/france/provence-alpes-cote-d-azur.map).

So, I hope that you will be able to find what's wrong with the OSMDroid tile cache because I was very waiting for an offline maps solution ... :-/

**Comment by spyhunter99** [comment]
I can't reproduce the problem with osmdroid. Did you try deleting the cache
on your device at /sdcard/osmdroid/tiles? it may be in a different location
on your device. wherever getExernalStorage maps too

**Comment by 2ndGAB** [comment]
Strange but sounds like the problem is from my side.
Not time now. I'll check it back next week.
Thanks.

**Comment by 2ndGAB** [comment]
So, you were right spyhunter99, I checked my code again and I had a problem correctly clearing the cache folder so your adapter works fine.
Thanks a lot for your very very usefull job and sorry for my mistakes.

**Comment by spyhunter99** [comment]
ready to merge, as far as i can tell

**Comment by 2ndGAB** [comment]
Perfect Spyhunter99

**Comment by spyhunter99** [comment]
merged
