### ISSUE TITLE
setScrollableAreaLimit() and setMapRotation()

### ISSUE THREAD

**Issue by pgrupa** [osmdroid/osmdroid#282]
When setting a map rotation using setMapRotation and a scrollable area limit using setScrollableAreaLimit, the scrollable area limit does not seem to work correctly, not taking account the actual map rotation. Setting map rotation to a value other 0 will cause the scrolling bounds to trigger as if the map was never rotated. I'm using the latest source from master.

Example: setting the map rotation to 90 will cause the left side of the map stop scrolling when the east bound is reached, altough the left of the map is really south. This causes strange behaviour for various zoom levels. In my case, I could scroll outside the west and east bounds (top and bottom on my may), but could not reach the south and north bound (left and right on my map).

Does anyone have pointers how to make setScrollAreaLimit rotation aware?

**Comment by spyhunter99** [comment]
interesting. definitely a bug, if you fix it, please open a pr

**Comment by spyhunter99** [comment]
to add, i'm not entirely sure what right looks like here. I think you'll probably always have some area of the view that's outside of the scroll limit with rotation. See MapView.java:912. A simpler solution would be to not allow rotation when setting the bounds.

**Comment by spyhunter99** [comment]
@pgrupa so what do we do about this?

**Comment by monsieurtanuki** [comment]
@spyhunter99 The bug described here doesn't happen anymore: the bounding box is _relatively_ respected for all map rotations, as tested again in `SampleLimitedScrollArea` adding the following:
 ````java
mMapView.getOverlays().add(new RotationGestureOverlay(mMapView));
````
_Relatively_, because as usual with map rotation the computations take place on the 0 degree map, and then the map is rotated.
I don't know what the expectations are - as I never use myself either rotation or bounding box limit.
For instance, in the following screenshot I could not move anywhere. Because in the corresponding 0 degree map the bounding box was contained in the screen. But if you add map rotation, I don't know if it makes sense: should we be able to pan the map to the left until we reach the bounding box's top left corner?
![image](https://user-images.githubusercontent.com/11576431/33371188-27e73864-d4fa-11e7-8ddb-f779de6a972e.png)
