### ISSUE TITLE
Support Higher Zoom Level Than 22

### ISSUE THREAD

**Issue by schrieveslaach** [osmdroid/osmdroid#329]
At the moment osmdroid is restricted to use a maximum zoom level of 22 even if the tile server provides much higher resolution, for example 26.

The implementation of `TileSystem` restricts the maximum zoom level to 22. Is it possible to raise the maximum to higher numbers? It seems that using higher zoom level than 22 cause integer overflows. 

I started a new fork trying to address this problem but it is not working. I appreciate any help on that.

**Comment by spyhunter99** [comment]
See the doubles branch

**Comment by spyhunter99** [comment]
do you have a publicly accessible source for zoom 22 for testing?

**Comment by spyhunter99** [comment]
I just ran some tests on the doubles branch. Although you can zoom in as far as you want, there's still some overflow happening somewhere. When zooming out, the map is centering somewhere unexpected past zoom 21

**Comment by spyhunter99** [comment]
i just did a quick look into this. It's going to be a lot of work but not impossible.
scrollable area limits will need to be reworked

i also tried to narrow down where the overflow is i think i found it in Project.toMercatorPixels(int x, int y);

Root cause: we're using android's View.scrollTo to handle planning the map around. It uses an x,y coordinate in screen pixels that is integer based.  To overcome the overflow issue, we'd have to write our own mechanism to pan the map that's not based on integers nor based on android's View class. Looks like a ton of work.

**Comment by schrieveslaach** [comment]
@spyhunter99, I ported `TileSystem` to long and I came across the same issues. In a lot of places I needed to convert from long to int... I also tried to `PointF` and `RectF` but I do not have a running version yet. 

What would be good approach to implement this? I'm not very familiar with the internal...

**Comment by spyhunter99** [comment]
This is my current understanding and i'm probably wrong...

Essentially, at every zoom level, it creates a canvas that is equal to the size of the tile in pixels * the total number of tiles on at the zoom level. It doesn't actually allocate the ram for it but that's the size of the canvas. When scrolling (panning on the map), android moves the current view of the canvas around which triggers tile loading, etc. Android uses screen coordinates for everything (integer based). At a high enough zoom level, the conversion from lat/lon to pixel coordinates results in a value > Integer.MAX. The negative value will then send the map view flying off somewhere else. We use Android's scrolling mechanism that requires a Point instance (Integer coordinates). If we can get rid of that and use either doubles or longs everywhere, then the problem would be solved. However, using our own scrolling mechanism is not a trivial task

If you look at the files i touched with the last commit, MapController line 225, I put a fixme in place to identify where the first occurrence of overflow is that I've found.

**Comment by spyhunter99** [comment]
@schrieveslaach to more directly answer your question, i think we need some kind of custom view that does not rely on android's scrolling mechanism nor the canvas coordinate system.

**Comment by spyhunter99** [comment]
attempted to convert to SurfaceView, this will be problematic because we use childViews a lot. I also couldn't get anything to render.

attempted to extend View and ViewGroup, changing all integers to long. For some reason, extending "View" is not resolving any of the protected or public methods or variables.

**Comment by schrieveslaach** [comment]
This is still on our agenda. I could work on Thursday on it. Do you think I can support you on this?

**Comment by spyhunter99** [comment]
absolutely!

**Comment by schrieveslaach** [comment]
Do you have anything special in mind? Any commits, branches, ...

**Comment by spyhunter99** [comment]
just make a branch with this ticket number and go to town. all of the attempts i've done have not been pushed nor committed (just as stashes).

**Comment by spyhunter99** [comment]
I think we can use a long based coordinate to keep track of what the view port is looking at, however this would require writing our own mechanism for scrolling and panning the map.

**Comment by atoone** [comment]
It might make sense to write a 'shim' that sits between the view and the OSMDroid code, rather than extending the view itself. The shim could translate view pixel movements into the smallest logical 'world' pixel movements (longs? floats?) and OSMDroid queries that rather than the underlying view.

**Comment by spyhunter99** [comment]
I absolutely agree. It's probably the only logical solution aside from
rewriting everything for opengl

**Comment by atoone** [comment]
As an aside, where is the best place to discuss general OSMDroid development? The Google Group appears dead and the latest release has thrown up a lot of questions about offline caching and other features.

**Comment by spyhunter99** [comment]
Great question.  I wish google groups had notifications. I don't check it too often

**Comment by gruelfin** [comment]
Will there be support for higher zoom levels and if yes, is there an ETA for this?

**Comment by monsieurtanuki** [comment]
Trying to do our own `View.onScroll` method would be very risky.

As already mentioned, the problem is that we use a virtual canvas that includes the whole world, and that we use `int` offsets to center the map: standard Android `View.getScrollX/Y`. We even store the scroll values into preferences, in order to keep the same map center. And that doesn't work very well: if you center your map on a location and tilt your smartphone, the map center will be offset by the difference between your `View`s width and height - my personal end-user assumption would be that the center would be kept. And that regardless of very high zoom levels.

And if we used the map center instead of the scroll offsets? In the `Projection` class we would compute `long` offsets according to the map center (for instance Tokyo in zoom 35), and compute `Point`s relatively to this map center. Or maybe `PointL` (`long` version of `Point`, to be created), which would give us the ability to handle the overflow:
* this is the current zoom and the current map center (Tokyo level 35)
* compute the corresponding offset for map center
* please add this location (Paris) => compute the `PointL`
* display the location => no I won't, Paris' `PointL` is beyond the +- 2^31 overflow

Something like that.

**Comment by monsieurtanuki** [comment]
For the record, just managed to go up to level 29 :)

Now I need to clean the code, and I should be able to PR within a week.

**Comment by spyhunter99** [comment]
bravo!

**Comment by spyhunter99** [comment]
done, thanks to @monsieurtanuki
