### ISSUE TITLE
Add option to set a `drawable` as tile loading background

### ISSUE THREAD

**Issue by roostaamir** [osmdroid/osmdroid#330]
The only thing that I saw in the api that can "somehow" change the loading background are two following functions:

```
map.getOverlayManager().getTilesOverlay().setLoadingBackgroundColor()
map.getOverlayManager().getTilesOverlay().setLoadingLineColor();
```

I want to be able to change it to a drawable stating an error. Or at least add an option that when user enters an area with now tile to show, an event be raised that we can show an error dialogue for example

**Comment by spyhunter99** [comment]
You can probably override the tile loader to return a default image or something to that effect when no tiles exist. I attempted something like that a while ago but was unsuccessful

**Comment by roostaamir** [comment]
what class do you think  is responsible for this effect? Could you share your existing knowledge with me a little about you idea?

**Comment by spyhunter99** [comment]
try MapTileProviderArray.mapTileRequestFailed

**Comment by spyhunter99** [comment]
So there is no "loading" image. We can add a method to set a default image for tiles that cannot be loaded at all. Having an image that's displayed immediately than replaced with the actual tile is done with the TilesOverlay. I just modified it to have a setter. The "loading" drawable is only displayed when the user scrolls past the tiles that are currently cached on device/memory/etc. Zoom in and out typically doesn't show the "loading" tile since it uses a scale animation to stretch the previous tile

**Comment by spyhunter99** [comment]
so that should get you going. reopen, comment back, or open a PR if this doesn't meet the need or if there's an improvement
