### ISSUE TITLE
Cache and download tile problems

### ISSUE THREAD

**Issue by zhaoxuhui** [osmdroid/osmdroid#384]
Q1:
The osmdroid default tile cache is 
`/tiles/SourceName/LayerLevel/ColumnNumber/RowNumber.png.tile`
For example,the Mapnik, layer level 3,row number 2, column number 6 tile,the path will be like this:
` /tiles/Mapnik/3/6/2.png.tile`
Can I change the path?Bacause the project I'm working on has some other request.I have to store tiles in path format like this :
` /tiles/SourceName/[L]LayerLevel/[R]RowNumber/[C]ColumnNumber.png`
For example the path will be :
`/tiles/Mapnik/L3/R2/C2.png`
So what should I do to deal with this?How to use the cacheManager?

Q2:
My project also requests that the tiles should stored in one database file ,such as the Berkeley Database.And then we can read tiles from the file.So where can I learn something about osmroid reading database file?I didn't find much info about this in the osmroid wiki.

I'm confused with these two problems these days.Thanks~

**Comment by spyhunter99** [comment]
You can modify or make your own implementation of IArchiveFile and register it with the ArchiveFactory. That's for just reading permanent offline tile archives. There's a few implementations, namely ZipFileArchive, DatabaseArchive, MBTilesFileArchive, GEMF, etc.

For the expiring cache of downloaded tiles, there's the IFilesystemCache which has a the TileWriter ( raw file system storage) and the SqlTileWriter. The CacheManager can also use SqliteArchiveTileWriter, which will create permanent tile archives on device (sqlite based)


Since you can override and register your own IArchiveFile implementation, it's probably the most flexible at the moment.

The IFilesystemCache can also be overridden at construction time of the MapTileProvider. See MapTileProviderBasic

**Comment by spyhunter99** [comment]
not sure if there's anything else i can provide for this. reopen if it's still an issue.
