### ISSUE TITLE
Map projection and  coordinate question

### ISSUE THREAD

**Issue by zhaoxuhui** [osmdroid/osmdroid#420]
When I use the map of mercator the map shows normally.
![screenshot_2016-09-15-20-43-28-870_com example my](https://cloud.githubusercontent.com/assets/17122056/18550704/afec283c-7b87-11e6-9d24-530c72e8dc32.png)

But when I use the map of projection of lat/lon ,it may shows wrongly.It has something wrong with latitude,but longitude is ok.
![screenshot_2016-09-15-20-43-14-960_com example my](https://cloud.githubusercontent.com/assets/17122056/18550472/9cd1a3ea-7b86-11e6-8738-f1455b1bc942.png)
As you can see in the picture.The lat 0 is not at the real equator,but at the conjunction of map and blank area.The latitude is not right ,so when I try locate my location it also comes to a wrong place.So how do I do to solve this problem?Can I get rid of the blank area?Thanks~
Here is the WMTS sever url I use in the second picture:
http://t0.tianditu.com/ter_c/wmts?service=wmts&request=GetTile&version=1.0.0&LAYER=ter&tileMatrixSet=c&TileMatrix={TileMatrix}&TileRow={TileRow}&TileCol={TileCol}&style=default&format=tiles

**Comment by spyhunter99** [comment]
The project is wrong. Osmdroid uses the Web Mercator project out of the box. If you change tile sources to something other than Web Mercator, you'll also need to change the projection implementation. Since we don't have any other implementations, you're left with the following options

- Convert your web source and/or map data to use web mercator
- write your own project implementation for the projection (looks like equirectangular)

**Comment by spyhunter99** [comment]
i'm guessing that the lack of response means that the question was answered sufficiently. good luck. reopen if needed
