### ISSUE TITLE
Multitouch 2-finger zoom jumps after touchup

### ISSUE THREAD

**Issue by miguel-porto** [osmdroid/osmdroid#507]
Hi, 
there seems to be a new bug in 5.6.2 which was not happening in 5.5: when zooming with 2 fingers, after the gesture ends, the map jumps to another place, instead of keeping centered in the same location it was immediately before the gesture ends. This can be replicated in the base sample of the sample app.
Cheers!

**Comment by spyhunter99** [comment]
strange, i don't think that part of the code was changed recently. I think the fix has something to do with temporarily disabling fling

**Comment by spyhunter99** [comment]
#269

**Comment by miguel-porto** [comment]
I tried totally disabling fling, but the issue remains. It also happens when, after 2-finger zoom, only one finger is released: the map immediately jumps (i.e. it doesn't animate like fling does). It also happens in the "OSMDroid Sample map (start here)", can you replicate?

**Comment by miguel-porto** [comment]
I confirm that in the previous version 5.5, this did not happen (both when releasing one finger only, or two fingers).

**Comment by miguel-porto** [comment]
Ok I found the origin of the issue. If I revert this line back:
https://github.com/osmdroid/osmdroid/commit/470a062d351501cb49a84c51dafc51b6d47c3c87#diff-3877d71d98d1f9f9c37d26719ad294e8R109
to
`return TileSystem.PixelXYToLatLong(x - mOffsetX, y - mOffsetY, mZoomLevelProjection, reuse);`

The issue disappears. It's something in the `unrotateAndScalePoint()` !

**Comment by spyhunter99** [comment]
good find, i can revert the change, reopen the old ticket, then cut a release to get you up and running

**Comment by spyhunter99** [comment]
#459

**Comment by spyhunter99** [comment]
looks like the problem is probably emitting from here


W/System.err( 3255):    at org.osmdroid.views.Projection.fromPixels(Projection.java:108)
W/System.err( 3255):    at org.osmdroid.views.Projection.<init>(Projection.java:67)
W/System.err( 3255):    at org.osmdroid.views.MapView.getProjection(MapView.java:323)
W/System.err( 3255):    at org.osmdroid.views.overlay.TilesOverlay.draw(TilesOverlay.java:181)
W/System.err( 3255):    at org.osmdroid.views.overlay.DefaultOverlayManager.onDraw(DefaultOverlayManager.java:121)
W/System.err( 3255):    at org.osmdroid.views.MapView.dispatchDraw(MapView.java:1108)

**Comment by miguel-porto** [comment]
Yep, that solved the issue, thanks! Zoom gesture in rotated maps (in the sample app) also works as expected now.
