### ISSUE TITLE
CacheManager download by points sometimes downloads 0/-1/-1 urls

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#512]
Not sure what's causing it, but giving the CacheManager a set of points with a min zoom of 0, max zoom 3 (or whatever) will attempt to download negative values for x and y coordinates, which is invalid

**Comment by spyhunter99** [comment]
paging @2ndGAB

**Comment by 2ndGAB** [comment]
used zoom levels are quite uncommon I think but...
Can I have te set of points used?

**Comment by spyhunter99** [comment]
I don't think the set of points matters too much, but the call was for min
zoom 0 to max zoom 15 for a short distance. I think the attempts to get
zoom 0 were yielded negative x y coordinates

**Comment by 2ndGAB** [comment]
I look at it.

**Comment by 2ndGAB** [comment]
Ok you are right, I think I fixed the bugs.

**Comment by spyhunter99** [comment]
roger that, i see 3 commits from today. I'll try to get them merged in today

**Comment by 2ndGAB** [comment]
SORRY SORRY

After deeper analysis, I realized that the fix was incorrect and can miss some tiles in case we are close to lat 0 or lon 0, mainly for usual zoom levels, so I made a correction this morning.
I also fixed `cleanArea()` which missed some tiles in case of GeoPoint list.
To keep only one call, I modified it to go outside of the bounds defined at each zoomlevel. As this job is very quick, I think that won't too much extra job even for 'classic' CacheManager use.

**Comment by spyhunter99** [comment]
Ok I'll check it out tonight

**Comment by spyhunter99** [comment]
i love the readme by the way!

**Comment by spyhunter99** [comment]
@2ndGAB can i steal your cache manager readme and images? You can still edit it in the osmdroid repo. hell you want i can probably get you write access

i'm appreciate the time you put into this

**Comment by 2ndGAB** [comment]
Yes you can, no problem.

**Comment by spyhunter99** [comment]
great it's been added
