### ISSUE TITLE
How to read,draw and manage polylines?

### ISSUE THREAD

**Issue by zhaoxuhui** [osmdroid/osmdroid#532]
I have a shape file(*.shp) of polylines.And I have read all the points.For each polyline I use a list of points to store them.And then new an polyline object to draw it.Doing this until it ends. 
But there are so many polylines and how I manage them?For example , deleting someone of them?How to distinguish one certain polyline from others?What is the proper way to load and draw many polylines at once?

polyLines is the list of different polylines .Each item represents a polyline and contains some points.

            Polyline polyline;
            List<List<GeoPoint>> polyLines = new ArrayList<>();
            for (int i = 0; i < polyLines.size(); i++) {
                polyline = new Polyline(MyActivity.this);
                polyline.setPoints(polyLines.get(i));
                polyline.setColor(Color.RED);
                polyline.setWidth(4);
                polyline.setInfoWindow(new BasicInfoWindow(R.layout.bonuspack_bubble, mMapView));
                polyline.setTitle("Polyline tapped!");
                mMapView.getOverlays().add(polyline);
            }`

And another question. While I draw so many polylines on the map, the app will become very slow and occupy much RAM.To solve this , I come up with an idea.We just load points in the Screen BoundingBox.
First,load points and store them in an database(sqlite file).And then write load points codes in the onScroll Event of MapListener.While we move on the screen , the BoundingBox changes,and we reload points and draw them.But I wonder is there any better ways to do this?

**Comment by miguel-porto** [comment]
In [SimpleFastPointOverlay](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/overlay/simplefastpoint/SimpleFastPointOverlay.java), this is done with an internal grid index, in which case only one point, at most, is drawn in each grid cell. This significantly speeds things up. A similar logic could be implemented for lines and polygons, but of course is a bit more complex.

**Comment by spyhunter99** [comment]
@miguel-porto i noticed that when panning the map, your sample tends to have a dynamic picture, meaning the dots seem to move around a bit, is that normal?

@zhaoxuhui there's been a bunch of threads on this topic, there are several solutions but the most the involve what you described. Only add things to the mapview when they are in the view. Limit the data as much as possible. Pro tip for polylines and polygons, when the zoom level changes, run an agreesive point reduction algorithm. I ran into a similar issue using shape files, converted to kml for MGRS gridlines, planet wide. Turns out a single 1km grid had waaay too many points. After running the reduce multiple times i was able to get something to display with reasonable performance but at an accuracy cost. I haven't revisited it in a while.

Question: how are you reading the shape files on device? totally want that code lol

**Comment by miguel-porto** [comment]
@spyhunter99 that's the price you pay for the high rendering speed... dots flicker because only one, at most, is drawn per grid cell, but the one that gets drawn is not predictable, and during panning it may change. Yes, this could be improved, but still didn't have time. I also don't like it, but I still think it's acceptable for the benefit you have. But the points stay in the right place, you can see when zooming in, everything gets fine.

**Comment by spyhunter99** [comment]
Listening for zoom/scrolls, you can use the logic in this example do so
https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/data/HeatMap.java. There's a few others in the same package that are related.

**Comment by zhaoxuhui** [comment]
@spyhunter99 OK,I'll upload codes few days later to github so that you can see it.

**Comment by spyhunter99** [comment]
haven't heard anything back in this in many months. closing for now. reopen if it is still an issue
