### ISSUE TITLE
Cannot find documentation on using cachemanager osmdroid bonus pack?

### ISSUE THREAD

**Issue by aritrabasu104** [osmdroid/osmdroid#637]
@MKergall 
I would like to
1.Use the cached tiles
2. cache the tiles when the bounding box changes
3.update the expired tiles
4.set the cache size(say 50 mb)

**Comment by kasual1** [comment]
Yes same here.
In my app I want to reduce mobile data usage as much as possible by using cached sqlite tiles. Currently I don't know how to check if tiles for a certain bounding box are available and how to use them. Does osmdroid automatically do that for me or do I have to implement the tile caching logic myself. It would be nice to have some guidelines on this.

Apart from that, keep up the great work. It perfectly fits my project needs and it definitely can keep up with some of the paid map sdk solutions out there :)

**Comment by monsieurtanuki** [comment]
I guess what you're looking for is [CacheManager](https://github.com/osmdroid/osmdroid/wiki/Cache-Manager). More specifically for your needs, method `downloadAreaAsync` would do the trick.

If I go a bit further in my explanations: every downloaded tile is stored in the sqlite db and will stay there unless the db exceeds its size limit. In that case the elder tiles will be removed.

Using `CacheManager` from version 5.6.5 you can also check if tiles are already in the db.
It will not be as straightforward as downloading - which is a standard need - but it's not that complicated.

Basically a `CacheManager` executes a `CacheManagerAction` on each tile of a given tile set (e.g. computed from a bounding box, a minimum and a maximum zoom).
In order to check if a set of tiles is already in the db, you have to:
* create your own class that extends `CacheManagerAction`, and name it `CheckTileAction` for instance
* in this class, override method `tileAction` and use method `CacheManager.checkTile` in order to check if the tile is already in the db or not
* create an instance of `CacheManager`
* create an instance of `CacheManagerTask` that uses an instance of `CheckTileAction` and defines the set of tiles
* run the whole thing using `CacheManager.execute`
* et voilà !

I hope this helps.

**Comment by aritrabasu104** [comment]
@monsieurtanuki or @MKergall can u throw some sample codes?
It would be of great help.

**Comment by monsieurtanuki** [comment]
Sample codes can be found in class [`CacheManager`](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/cachemanager/CacheManager.java), for instance in method `public CacheManagerTask downloadAreaAsync(Context ctx, BoundingBox bb, final int zoomMin, final int zoomMax)` and its use of method `public CacheManagerAction getDownloadingAction()`

**Comment by spyhunter99** [comment]
The sample app "Open Map" in the play store, has examples of doing this.
