### ISSUE TITLE
Geopackage, support vector tile sources

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#665]
Current geopackage support is limited to raster tile sets only. The libraries we use to provide tiles in osmdroid friendly formats is provided by NGA. They have support for gmaps with vector data, so it's definitely possible, but a bit of work will be required to mirror their gmaps centric adapters in osmdroid polyline/polygon data structures

Related issues
#618  #246 #180

**Comment by monsieurtanuki** [comment]
I'm interested. Regarding the vector tile sources, couldn't we use something like #660?

**Comment by spyhunter99** [comment]
i think what the nga code does is take the geopackage lines and areas and points and converts them into google map's equivalent of polyline, polygon and marker. All we have to do is mirror that code. It may be better to put that code base in NGA's hands, then we can just import their library here. The problem with that is that it will create a circular dependency situation. We need their library to render the features, they need our aar to get the classes for marker, polyline, etc

**Comment by spyhunter99** [comment]
perhaps @bosborn can provide some guidance or at least point us in the right direction. I think what we need for this ticket is FeatureDaos and basically an osmdroid implementation for the following package https://github.com/ngageoint/geopackage-android-map/tree/master/geopackage-map/src/main/java/mil/nga/geopackage/map/geom. Referencing the readme, https://github.com/ngageoint/geopackage-android-map it looks like it is a Feature Tile. I'm not sure actually.

**Comment by spyhunter99** [comment]
https://github.com/ngageoint/geopackage-android/issues/18

**Comment by bosborn** [comment]
You are correct, the code in the [geopackage-android-map geom](https://github.com/ngageoint/geopackage-android-map/tree/master/geopackage-map/src/main/java/mil/nga/geopackage/map/geom) folder is used to convert between the GeoPackage Well-Known Binary (WKB) geometries and Google Maps geometries.  [GoogleMapShapeConverter](https://github.com/ngageoint/geopackage-android-map/blob/master/geopackage-map/src/main/java/mil/nga/geopackage/map/geom/GoogleMapShapeConverter.java) is the starting point for that logic.  The shapes that have markers in their name are for shape editing purposes where a marker is on each corner ([example](https://github.com/ngageoint/geopackage-mapcache-android/raw/master/screenshots/screenshot4.jpg)).  So if you are wanting the raw geometries on the map this would be the place to look.  Not knowing much about osmdroid, I assume you have your own point, line, polygon shapes to convert to.

If you would prefer to instead use tiles drawn from the features, that's where the feature tile stuff comes in.  Google Maps starts to suffer with a large number of raw shapes, so drawn tiles are what we prefer to use.  Luckily a lot of this logic [exists in the base geopackage-android library](https://github.com/ngageoint/geopackage-android/tree/master/geopackage-sdk/src/main/java/mil/nga/geopackage/tiles/features) with Google map specific implementations in [geopackage-android-map](https://github.com/ngageoint/geopackage-android-map/tree/master/geopackage-map/src/main/java/mil/nga/geopackage/map/tiles/overlay).  We index the GeoPackage feature table using a mobile friendly [NGA GeoPackage extension](http://ngageoint.github.io/GeoPackage/docs/extensions/geometry-index.html) and draw the tiles on demand.

From the [geopackage-android](https://github.com/ngageoint/geopackage-android) README:

```java

...

// Index Features
FeatureIndexManager indexer = new FeatureIndexManager(context, geoPackage, featureDao);
indexer.setIndexLocation(FeatureIndexType.GEOPACKAGE);
int indexedCount = indexer.index();

// Draw tiles from features
FeatureTiles featureTiles = new DefaultFeatureTiles(context, featureDao);
featureTiles.setMaxFeaturesPerTile(1000); // Set max features to draw per tile
NumberFeaturesTile numberFeaturesTile = new NumberFeaturesTile(context); // Custom feature tile implementation
featureTiles.setMaxFeaturesTileDraw(numberFeaturesTile); // Draw feature count tiles when max features passed
featureTiles.setIndexManager(indexer); // Set index manager to query feature indices
Bitmap tile = featureTiles.drawTile(2, 2, 2);

...

```

[geopackage-android-map](https://github.com/ngageoint/geopackage-android-map) then wraps that logic for Google Maps, from the README:

```java

...

// Index Features
FeatureIndexManager indexer = new FeatureIndexManager(context, geoPackage, featureDao);
indexer.setIndexLocation(FeatureIndexType.GEOPACKAGE);
int indexedCount = indexer.index();

// Feature Tile Provider (dynamically draw tiles from features)
FeatureTiles featureTiles = new MapFeatureTiles(context, featureDao);
featureTiles.setMaxFeaturesPerTile(1000); // Set max features to draw per tile
NumberFeaturesTile numberFeaturesTile = new NumberFeaturesTile(context); // Custom feature tile implementation
featureTiles.setMaxFeaturesTileDraw(numberFeaturesTile); // Draw feature count tiles when max features passed
featureTiles.setIndexManager(indexer); // Set index manager to query feature indices
FeatureOverlay featureOverlay = new FeatureOverlay(featureTiles);
featureOverlay.setMinZoom(featureDao.getZoomLevel()); // Set zoom level to start showing tiles
TileOverlayOptions featureOverlayOptions = new TileOverlayOptions();
featureOverlayOptions.tileProvider(featureOverlay);
featureOverlayOptions.zIndex(-1); // Draw the feature tiles behind map markers
map.addTileOverlay(featureOverlayOptions);

...

```

The [FeatureIndexManager](https://github.com/ngageoint/geopackage-android/blob/master/geopackage-sdk/src/main/java/mil/nga/geopackage/features/index/FeatureIndexManager.java) can also be used to query the features behind the tiles.  In geopackage-android-map this wrapped by [FeatureOverlayQuery](https://github.com/ngageoint/geopackage-android-map/blob/master/geopackage-map/src/main/java/mil/nga/geopackage/map/tiles/overlay/FeatureOverlayQuery.java).

You can also generate static tiles ahead of time using [FeatureTileGenerator](https://github.com/ngageoint/geopackage-android/blob/master/geopackage-sdk/src/main/java/mil/nga/geopackage/tiles/features/FeatureTileGenerator.java).  These tiles are linked to the features using [this custom extension](http://ngageoint.github.io/GeoPackage/docs/extensions/feature-tile-link.html) so that feature tiles are only drawn when static tiles are not found.

**Comment by spyhunter99** [comment]
@bosborn thanks, that clears things up a bit. Osmdroid has a marker, polyline and polygon and also has limitations in terms of quantity added to the map. It is device dependent but somewhere about 1000 elements lines/polygons things start to go sour, but 2k it's very choppy. Markers on the other hand can be into huge numbers.

Moving forward, doing the line/polygon conversion might be a good first step with follow up efforts for the raster tile overlay. Since most of the code exists for gmaps, both should be easily adaptable to osmdroid.

**Comment by spyhunter99** [comment]
@bosborn i was able to get the feature dao > osmdroid marker, line and polygon classes working, for the most part. I of course, stupidly loaded the first geopackage i cound fine with features, containing the borders all of us states. naturally the performance was quite poor due to lack of optimization but the initial functionality is there.

@MKergall does the polygon class support "holes"?

**Comment by spyhunter99** [comment]
https://github.com/ngageoint/geopackage-android-map/issues/5

**Comment by spyhunter99** [comment]
i'm about 90% certain that most of these classes can be condensed and simplified. it looks like the added complexity was specifically for gmaps specific stuff

**Comment by spyhunter99** [comment]
never mind, answered my own question, yes polygon supports holes. Anyhow, got the tile tiles to work.
![image](https://user-images.githubusercontent.com/1975321/29745908-09ba302a-8a96-11e7-8805-34ca513fce7e.png) using this geopackage, performance is pretty good https://github.com/opengeospatial/geopackage/blob/gh-pages/data/states10.gpkg

**Comment by spyhunter99** [comment]
this branch still needs some work to clean up all the fixme classes in the feature to overlay converter and to potentially reduce the class footprint

**Comment by monsieurtanuki** [comment]
A very nice demo would be:
* color each state with red/blue depending on the 2016 elections, with alpha background and less transparent border
* clickable states, with a popup that gives the name of the state and the results

A very very nice demo would also:
* put Alaska and Hawaii in separate mini maps with relevant zoom levels
* give alternate access to the results as a `ListView`

**Comment by spyhunter99** [comment]
with the right geopackage database, this is possible.

**Comment by monsieurtanuki** [comment]
@spyhunter99 Once you're done with the fixme's and the merge I'll need your help in order to code this US election demo.

**Comment by spyhunter99** [comment]
@monsieurtanuki want to help? all that let is to make the style attributes  (i think). colors, stroke size, etc. I'm tied up with the wms support, which is a complex to say the least

**Comment by spyhunter99** [comment]
@monsieurtanuki regarding your demo idea. This ticket adds two additional geopackage features, a conversion utility to convert geopackage feature table data into osmdroid overlays, and a tile renderer that renders geopackage feature table data into tiles (that NGA wrote). 

Keeping that in mind, your idea for states with data and whatnot. This can be acomplished by editing the sample file that bosborn linked to and then altering the table data. I don't know enough about how database storage format to give you any further guidance than this.

**Comment by spyhunter99** [comment]
@bosborn sorry to bug you on this, but what is the purpose of `MultiMarker`. The javadoc lists it as "Multiple Marker object". Is it a collection of markers on the map that share the same icon with different locations? or is it something else?

**Comment by spyhunter99** [comment]
just added user overrides for styling. apparently either geopackage storage format or the nga package doesn't cover that aspect
![image](https://user-images.githubusercontent.com/1975321/30002874-cb45fada-9081-11e7-9fc6-c89f020821dd.png)

**Comment by monsieurtanuki** [comment]
Exactly what I had in mind - except that everybody voted for the Republicans in your map!
I assume that you have no control over this or that state: it's just a common style applied to all states.
Tell me when the demo is ready and PR'ed. I'll try to make the distinction between states.

**Comment by spyhunter99** [comment]
@monsieurtanuki haha yup, common color settings for the entire table. The good news is that the database does have the state names in the data. I'll look into seeing if it can be extracted in a logical and generic way

**Comment by spyhunter99** [comment]
![image](https://user-images.githubusercontent.com/1975321/30005733-f7ae2144-90b6-11e7-9f11-d276b7da7b7e.png)

**Comment by monsieurtanuki** [comment]
Awesome!

A few remarks:
* minimaps for Alaska and Hawaii would be great
* now that we have a bullet proof `MapView.zoomToBoundingBox`, a nice OnClick listener would not only display the state data but also zoom on the state borders
I believe that with those additional features, this demo would not only be a technical demo but also a nice showcase.

Less important, less relevant:
* strangely enough the great lakes do not appear at this zoom level - a bug from the tile source as they appear in lower and higher zooms
* a more standard version would have a white background instead of map tiles. At least we should be able to switch between white background / map tile background

**Comment by bosborn** [comment]
MultiMarker is the Google maps version of a MultiPoint geometry ("A restricted form of GeometryCollection where each Geometry in the collection must be of type Point").  So nothing special other than multiple points that have been grouped as part of a single geometry.  Similar to what MultiPolyline is to MultiLineString.

GeoPackage styling is not officially supported in the spec yet but will be in the future.  There is at least [one unofficial styling extension](http://www.geopackage.org/extensions.html) but it has not been adopted yet.  We style externally in our apps for now.

**Comment by spyhunter99** [comment]
@bosborn thanks for the clarification.
