### ISSUE TITLE
Promiscuous offline tile provider

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#688]
new feature for the offline users. alternate versions of the offline tile provider that ignores tile source names, providing the first tile available from any offline or cache source.

**Comment by MKergall** [comment]
Not sure for this one. Tile sources can be very different (eg satellite photos). Mixing that could look like a bug. 
At least, the feature should be optional.

**Comment by spyhunter99** [comment]
Definitely opt in. Not the default

**Comment by secaw** [comment]
Would be a great feature! E.g. in my use case I already created my own version of `DatabaseFileArchive` to make it source insensitive. Other file archives like MBTiles and GEMF are source insensitive by default. But I didn't manage to do the same with `ZipFileArchive`, which apparently has to have the source name (e.g. 'Mapnik') as filename ('Mapnik.zip') in order to match the source and thus be shown. Btw there's a related issue with `ZipFileArchive` as it doesn't read direct MOBAC zip exports in general, because MOBAC doesn't use the source names as filenames anyways.

**Comment by spyhunter99** [comment]
@secaw I have code for zip archives somewhere. Mobac uses whatever you enter for the layer name as the tile source.

**Comment by secaw** [comment]
@spyhunter99 Unfortunately it's a bit more complicated with Mobac and osmdroid zip:

- osmdroid `ZipFileArchive` expects a zip structure like this: CurrentTileSourceName.zip / [zoomlevel folders]
- Mobac export as 'osmdroid zip' does this: AtlasName.zip / ShortMapSourceName / [zoomlevel folders]

So they are not only incompatible just from the filename, but from the whole structure!

Besides that, having `ZipFileArchive` be source aware doesn't make much sense: Imagine you want to have two offline zip files e.g. one of Papua New Guinea and one of Brooklyn. Both would have to be named 'Mapnik.zip' in order to appear on your openStreetMap, so they could not be used simultaniously. That's why I think `ZipFileArchive` should be source unaware by default just like MBTiles and GEMF file archives.

The way I think about the great offline map functionality of osmdroid is, I'd like to make it most easy for users to include their own maps - meaning that they export them from Mobac, drop them into osmdroid folder on their device and are ready to use them, no matter which (online) tile source they have set. This is now working nicely for me with my custom `DatabaseFileArchive`, GEMF and MBTiles formats. I don't support zip files right now because of the above described filename source awareness and general incompatibilities with Mobac.

Of course there are different use cases, but that's why I think, an optional 'promiscuous offline tile provider' that works with all supported offline tile formats would absolutely be very helpful.

**Comment by MKergall** [comment]
@secaw I'm surprised about what you say of ZipFileArchive behaviour. 

Did you read this: https://stackoverflow.com/questions/22862534/download-maps-for-osmdroid/22868462#22868462

From what I tried (3 years ago), the filename didn't matter. I've been able to make use of 2 or 3 zip files simultaneously.

**Comment by secaw** [comment]
@MKergall Thanks for your comment.
You are right! I obviously got confused with my zip files when testing.

In order to correct myself:

- osmdroid `ZipFileArchive` expects a zip structure like this: AnyFilename.zip / CurrentTileSourceName / [zoomlevel folders]
- Mobac export as 'osmdroid zip' does this: AtlasName.zip / ShortMapSourceName / [zoomlevel folders]

So the file structure actually matches instead of what I said earlier and also I'm able to have several zip files simultaneously with the same source.
There remains a problem with the probable incompatibility between osmdroid CurrentTileSourceName and Mobac given ShortMapSourceName (not layer name like @spyhunter99 suggested) for many tile sources.

I'll try to come up with a source unaware version of `ZipFileArchive` for my own implementation.
Thanks again.

**Comment by spyhunter99** [comment]
@secaw I'll second @MKergall, zip file archive is absolutely Blah.zip/SourceName/Z/X/Y.ext

MOBAC sets the SourceName usually equal to the layer name or the name of the zip file.

Then in osmdroid, you can ask the IArchiveFile what sources are available

https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/tileprovider/modules/IArchiveFile.java#L37

Then set the ITileSource name appropriately. I even made a simple wrapper for this `FileBasedTileSource.getSource(name)`

Demo here:

https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/samplefragments/tileproviders/SampleOfflineOnly.java#L88

**Comment by secaw** [comment]
@spyhunter99 Thanks. I double checked that at least in zip file archive the SourceName is not taken from the given layer name, but from the internal 'short' source name (at least with one layer, maybe that changes with more layers?). But anyway I managed to implement my own source unaware `ZipFileArchive`, so that now I only have source unaware archive providers, which basically is the concept idea of this issue, isn't it..
