### ISSUE TITLE
Secondary tile overlay does not always display tiles

### ISSUE THREAD

**Issue by nijs9** [osmdroid/osmdroid#690]
I'm using osmdoird 5.6.5 in my Android application. I'm using a custom baselayer, and I add a second layer above it in this way:

baselayer:

````
final MapTileProviderBasic tileProvider = new MapTileProviderBasic(getApplicationContext());
        final ITileSource tileSource = new XYTileSource(getResources().getString(R.string.rp_cachemap), 6, 17, 256, ".png", tileserver);
        tileProvider.setTileSource(tileSource);
        final TilesOverlay tilesOverlay = new TilesOverlay(tileProvider, this.getBaseContext());
        tilesOverlay.setLoadingBackgroundColor(Color.TRANSPARENT);
````

overlay:

````
final MapTileProviderBasic anotherTileProvider = new MapTileProviderBasic(getApplicationContext());
        final ITileSource tileSource2 = new XYTileSource("tile_overlay_3",6, 17, 256, ".png", new String[]{"https://geoserver2.nodemapp.com/geoserver/"})
        {
            @Override
            public String getTileURLString(MapTile aTile) {
                String hello= getBaseUrl() + "gwc/service/gmaps?layers=nodemapp-public-mobile-with-cache&zoom=" + aTile.getZoomLevel() + "&x=" + aTile.getX() + "&y=" + aTile.getY() + "&format=image/png&viewparams=kind:hike;groupid:1&version=1";
                System.out.println(hello);
                return hello;
            }
        };
        anotherTileProvider.setTileSource(tileSource2);
        final TilesOverlay secondTilesOverlay = new TilesOverlay(anotherTileProvider, this.getBaseContext());
        secondTilesOverlay.setLoadingBackgroundColor(Color.TRANSPARENT);
````

set tiles on map:

````
osmMap.setTileSource(tileSource);
osmMap.getOverlays().add(secondTilesOverlay);
osmMap.invalidate();
````

Eveything is working fine, but when scrolling the map, sometimes there are some tiles not showing properly in the second overlay. When scrolling a little bit further, they are loaded. Is this a known bug?

**Comment by spyhunter99** [comment]
I have seen this issue with secondary tile overlays but I'm not entirely sure why. It's even present on the demo app. I think the sample has mapnik + some kind of road overlay (in blue). It's probably some kind of threading or concurrency issue. I'll make it as a bug and hopefully someone will look into further

**Comment by nijs9** [comment]
Thanks. In this way, adding a second layer is useless. I've tested for one day now, and lot of tiles aren't loading many times. Problem is not on server side, online tiles are always available.

**Comment by nijs9** [comment]
@spyhunter99 In post https://github.com/osmdroid/osmdroid/issues/52 you give this as a possible solution:

> although that solution may work, essentially, it should end up calling the
ondraw method again. It may be better to do an overlay scan and look for
overlays that extend tilesoverlay, then force a redraw on those

Can you help me to implement this?

**Comment by spyhunter99** [comment]
@nijs9 after looking at the apis, i think `map.invalidate();` is what you want. Not sure if it will fix this issue or not

**Comment by spyhunter99** [comment]
i tried it, didn't work to fix the demo apps, no idea why

**Comment by spyhunter99** [comment]
so this is fun. i just purge the cache and the one sample "Sample with tiles overlay" runs perfectly. "Sample with tiles overlay and a secondary tiles overlay" does not. If i turn on all the debug settings, the second sample runs perfectly. I cleared the cache in between each test. One item no tiles were displayed until i nudged the map, then they all showed.

Mapviews with just the single tiles overlay do not seem to be affected by this. I wonder...

**Comment by spyhunter99** [comment]
i looked at this again, https://github.com/osmdroid/osmdroid/pull/908 helps this slightly but i'm still unable to consistent loading behavior of the second tiles overlay. MapView.invalidate, postInvalidate, invalidate after a delay, invalidate in onResume., onFirstLayoutListener. None of them work. I've tried on both #908 and master with some progress but no concrete solution. If the debug settings for map tile downloading is turned on, then it loads consistently. After reviewing the code, there's no clear reason why this would effect anything.

**Comment by conej730** [comment]
I'm seeing the same behavior in v6.0.1.  It seems to be that when I'm adding a second layer for weather that since the tiles are not available right away (we're semi aggressively clearing the cache), then new tiles that are downloaded after the overlay is placed are not being displayed until the map is moved.  I was considering implementation the previously mentioned solution, but it does seem less than optimal to have to invalidate the map every time a new time is downloaded?  Also then when I zoom in and new tiles are being downloaded for that zoom level I'll need to move the map a few times to get all the weather tiles to show up.

**Comment by spyhunter99** [comment]
weather tiles? are you the weather now guy?

**Comment by conej730** [comment]
No I actually work for a flight tracking company.  So we like to put the weather on the map too.

**Comment by monsieurtanuki** [comment]
@conej730 
> it does seem less than optimal to have to invalidate the map every time a new tile is downloaded?

According to [Android docs](https://developer.android.com/reference/android/view/View#invalidate()) about `invalidate`:

> If the view is visible, onDraw(android.graphics.Canvas) will be called _at some point_ in the future. 

In short: `invalidate` is not sync, and it's safe to call several times as Android will refresh the display potentially only once. At some point.

Back to the current issue.

We have async tile downloads, and a `MapView`.
How do new tiles refresh the `MapView`: only because whenever a tile is _successfully_ downloaded, it calls (by default) a `Handler` of class `SimpleInvalidationHandler`, that explicitly calls `MapView.invalidate`.
Another way to refresh the `MapView` is to move/pinch the map.

And the problem so far with the secondary tile provider is that you have to _explicitly_ tell your provider how to behave when a tile is successfully downloaded. If not you just ask it to download tiles into the cache, regardless of the display. And you don't have to do it explicitly for the primary tile provider because it's done in `MapView.setTileProvider`.

Therefore you should add something like
````java
anotherTileProvider.setTileRequestCompleteHandler(mMapView.getTileRequestCompleteHandler());
````
in your code.

In the meanwhile I'm fixing the "Sample with tiles overlay and secondary tile overlay" demo that doesn't work for the same reasons - I will PR within an hour.

Tell me if it works.

**Comment by conej730** [comment]
@monsieurtanuki Thanks that worked out great.

**Comment by monsieurtanuki** [comment]
@conej730 Excellent!
