### ISSUE TITLE
MapView.LayoutParams/InfoWindow imprecision in high zoom levels

### ISSUE THREAD

**Issue by b3nn0** [osmdroid/osmdroid#693]
Hi,
MapView.LayoutParams seem to have inaccuracies in high zoom levels, which can e.g. be seen with the InfoWindow.
I'm pretty sure that this is related to some float rounding in the rendering process, as the imprecision increases for the coordinates in the lower right corner of the coordinate system, and is practically zero for the top left corner.
I've created a video where you can see the problem (it's my own implementation of something similar to an InfoWindow that also uses MapView.LayoutParams. I could also reproduce it with the OsmDroid samples from Google PlayStore. Not as drastically however, as they don't allow for such high zoom levels):
https://youtu.be/SKIEbTMXkss
As you can see, the InfoWindow becomes very "jumpy" when scrolling the map, so it is not actually placed at the correct location any more.

Note that I'm also convinced that this is not directly an OsmDroid problem. During the onLayout phase, the coordinates seem to be quite fine. I guess the Android rendering pipeline will at some point convert the integer Point objects to floats, triggering the issue.
For that matter, I also think that this is closely related to https://github.com/osmdroid/osmdroid/issues/329 in two ways:
1. To support high zoom levels, this needs to be fixed
2. I think it would be fixed automatically when implementing a custom long or double based scroll system in combination with only a small canvas, rather than one spanning the whole world, as the coordinates wouldn't become so big that float rounding during rendering is a problem.

**Comment by marcelr** [comment]
Unfortunately, osmdroid comes to its limits when working with centimeter accuracy RTK-GPS.
Supporting higher zoom levels without loss is essential in such environments.
+1 vote for Long instead of Integer processing

**Comment by spyhunter99** [comment]
We rely on androids view scroller for panning the map which is in based. That's the blocking item

**Comment by monsieurtanuki** [comment]
As I described in #329, I think the problem is not really in the view scroller.

We have our *actual screen*; typically about 800x600 pixels.
We can work on a *virtual big canvas* square with 2^32 values for X and Y: that's where we draw things (limited to ìnt` values because of Android). As we would use a geo center offset, that will mean canvas coordinates between Integer.MIN_VALUE and Integer.MAX_VALUE.
There will be a *projection* square with (tileSize * 2^zoom) values for X and Y: that's where we project our geo points. Starting from 0.
There will be an *offset projection" square with (tileSize * 2^zoom) values for X and Y, from (-(tileSize * 2^zoom) / 2) to ((tileSize * 2^zoom) / 2 - 1).

How to I compute from a geo point to X/Y for a given zoom?
* I project this geo point into the corresponding `long` coordinates (as we do now, but now as `long`, starting from 0) (we're in the *projection*)
* I apply the map center offset (basically the coordinates of the map center computed as in previous step) (we're in the *offset projection*)
* If the offset projection coordinates fit into `int` and therefore fit into our *virtual big canvas*, that means we can try to display the marker - of course it will be displayed only if it also fits the *actual screen* limits.

Works like a charm for single markers, that can easily by dismissed (id est not drawn) if there are beyond visiblity when the offset projection coordinate don't fit into `int`.
But what shall we do with `Polygon`s corners that are beyond visibility? Potentially we still need to display them, not because we will see them but because we may see the segments coming to/from them.

I suggest that in the invisible `Polygon` corners cases we compute a visible point (*virtual big canvas* wise) as a "border approximation":
* from `long` coordinates that don't fit `int` values
* we compute the `int` intersection X,Y of
* a segment from the map center to those coordinates
* with the `int` square border { [MIN_VALUE,MIN_VALUE], [MIN_VALUE,MAX_VALUE], [MAX_VALUE,MAX_VALUE], [MAX_VALUE,MIN_VALUE] }

What do you guys think, about the whole solution and about the approximation for invisible `Polygon` corner?

**Comment by spyhunter99** [comment]
i was suggesting that we use a virtual canvas of type long which will obviously increase the max zoom level significantly. Then the issue is getting android's canvas to work correctly again, since it's int based. I did some experiments with this and the largest blocking issue for this path is the view scroller. The code is rather complex for it. If someone goes down this path, they would then need to translate from the android int canvas to the long canvas, basically tracking some offsets to figure out what part of the world to render.

**Comment by monsieurtanuki** [comment]
Just experienced a glimpse of double/long issues with large numbers:
```java
final long roundingIssueLong = (Long.MAX_VALUE-1)/2; // 4611686018427387903
Assert.assertEquals(roundingIssueLong, (double)roundingIssueLong, 0.); // when compared as double, even with 0. as delta: passes
Assert.assertEquals(roundingIssueLong, (long) (double)roundingIssueLong); // when compared as long: fails (actual is 4611686018427387904)
```

**Comment by monsieurtanuki** [comment]
The scale labels are computed in `ScaleBarOverlay.scaleBarLengthText(int meters)`..

Of course the `int meters` parameter is not relevant anymore. The type can still be `int` (potentially `long`), but what _minimum_ metric unit would make sense? Millimeters?

Today the labels in the metric unit are:
* "_i_ km" if the scale is above 5km
* or "_i.j_ km" if the scale is above 200m
* or "_i_ m"

What would the units and the thresholds be for the scales below the meter (for metric, imperial and nautical systems)?

Thank you for your help!

**Comment by monsieurtanuki** [comment]
I just noticed about the "int/long scroll" issue: even if we fix it we'll be limited to zoom level 29 in a first approach.

Why? The formula in order to compute the primary key in `SqlTileWriter` for SQLite table "tiles" is
```java
(((zoom << zoom) + x) << zoom) + y
```

The maximum possible zoom is therefore 29, which gives us enough space for:
* y (29 bits)
* x (29 bits)
* zoom (5 bits) (in order to code 29)
* total: 63 (29 + 29 + 5) bits used

I believe that zoom level 29 is high enough.
If needed there are solutions to bypass this limit, for instance:
* creating one table per zoom level - the index can be calculated as `x << 32 + y`, and that will give us a max zoom of 32
* splitting the SQLite table's primary key in several columns x, y and zoom, which will give us max zoom around 64 (pretty high, isn't it?)

**Comment by monsieurtanuki** [comment]
@b3nn0 I delivered #329 which goes up to zoom level 29.
Could you check if it solved your issue?

**Comment by b3nn0** [comment]
Just updated to current master and compiled.
Great work on the zoom level. Really appreciated.
However, MapView.LayoutParams doesn't seem to work at all any more, I think. Neither in low, nor in high zoom levels. Currently trying to collect more information about the issue.

**Comment by b3nn0** [comment]
I was able to fix it with a simple modification to MapView.myOnLayout():
```
-                               getProjection().toMercatorPixels(mLayoutPoint.x, mLayoutPoint.y, mMercatorPoint);
-                               final long x = mMercatorPoint.x;
-                               final long y = mMercatorPoint.y;
+                               final long x = mLayoutPoint.x;
+                               final long y = mLayoutPoint.y;
```

I think the imprecisions are better, however, there seems to be a missing call to requestLayout().
When scrolling the map, the position doesn't update at all until i remove/readd the child view.

**Comment by monsieurtanuki** [comment]
Your suggestions look fine to me. Thank you for your fix! Feel free to PR.
