### ISSUE TITLE
MapView Rotation And 3D or 2.5D Mode

### ISSUE THREAD

**Issue by AliKhoshraftar** [osmdroid/osmdroid#715]
i want to rotate map with 2 finger circular move and rotation in x-axis with 2 finger Up and Down move just like navigation map views.
how can i implement this ?

**Comment by spyhunter99** [comment]
- we don't support 3d or 2.5d
- rotation is supported, see the wiki https://github.com/osmdroid/osmdroid/wiki/How-to-use-the-osmdroid-library#how-to-enable-rotation-gestures
- two finger zoom in/out gestures are not supported but probably isn't too hard to implement. The short answer to your question is, I don't know

**Comment by spyhunter99** [comment]
You'd have to modify this class
https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/metalev/multitouch/controller/MultiTouchController.java

to detect a 3 finger gesture, then call the corresponding zoom in/zoom out functions. It may be worth waiting until 6.0 is cut, since that has floating point zoom

**Comment by spyhunter99** [comment]
operation timeout. please reopen or comment back if you have further questions
