### ISSUE TITLE
Getting error on Adding osmdroid-android as a module

### ISSUE THREAD

**Issue by mf-mindcrewtech** [osmdroid/osmdroid#755]
I am getting error on Adding osmdroid-android as a module, 
Error:Cannot get property 'pom' on extra properties extension as it does not exist.

Can anyone plz let me know, how can i resolve the error.

NOTE :: I don't want to compile gradle dependency.

**Comment by spyhunter99** [comment]
Did you change grails versions or gradle android plugin versions?

On Oct 31, 2017 5:28 AM, "MF" <notifications@github.com> wrote:

I am getting error on Adding osmdroid-android as a module,
Error:Cannot get property 'pom' on extra properties extension as it does
not exist.

Can anyone plz let me know, how can i resolve the error.

NOTE :: I don't want to compile gradle dependency.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/osmdroid/osmdroid/issues/755>, or mute the thread

**Comment by mf-mindcrewtech** [comment]
Did you change grails versions or gradle android plugin versions?

@spyhunter99 , what do you mean by this??

**Comment by spyhunter99** [comment]
https://github.com/gradle-fury/gradle-fury/blob/develop/README.md

**Comment by spyhunter99** [comment]
to add, there's a number of incompatible (to gradle fury) setups for gradle + gradle-android plugins. i'll see if i can update the osmdroid parts for the newer gradle fury, which will get us a larger range of support gradle versions

**Comment by spyhunter99** [comment]
closing due to lack of feedback, comment back if this is still an issue
