### ISSUE TITLE
MBTiles repeating endlessly

### ISSUE THREAD

**Issue by DaniLecx** [osmdroid/osmdroid#758]
I load my .mbtiles map from the assets folder, the problem is that it's displaying an infinite number of maps not only one.

I tried to fix it with map.setScrollableAreaLimit(map.getBoundingBoxE6()); but it is deprecated and doesn't work anymore, is there a way to get around this?

**Comment by monsieurtanuki** [comment]
About `MapView.setScrollableAreaLimit` being deprecated: use `MapView.setScrollableAreaLimitDouble(BoundingBox boundingBox)` instead.
But this is not supposed to fix your display issue.
What is the value of `map.getBoundingBox()`?

**Comment by Claragar** [comment]
The thing is i'm not using a real map, it's a game map converted to mbtiles, so i don't really know how to set the limits right because i don't have the same notion of latitude and longitude. I just want to display it once and not multiple times.

**Comment by monsieurtanuki** [comment]
`MapView.setScrollableAreaLimit` was recently fixed: that would explain why you see a difference.

You're using `MBTilesFileArchive`, right? What I can do is to develop methods that computes the map limits of a `MBTilesFileArchive`. And you could use those limits in your call of `MapView.setScrollableAreaLimitDouble` (instead of using `map.getBoundingBox()`).
Do you think that would solve your problem?

**Comment by spyhunter99** [comment]
It's repeating endlessly? Try setting tin the minimum zoom to 3

**Comment by Claragar** [comment]
I think the best solution for now is like @spyhunter99 said, set the minimum zoom so i don't see the map wrapping around. Even though i hoped i could zoom back a little a see a 'blank' space around the map instead of repeating maps.
When i set `map.setScrollableAreaLimitDouble(new BoundingBox(90, 180, -90, -180));` the map bounds work on the South and East side but North and West sides make a jump to the initial position when i go past the bounds instead of blocking the map.

**Comment by spyhunter99** [comment]
There's on going work and a PR to resolve this for 6.0. It is surprisingly complex. See #183

**Comment by spyhunter99** [comment]
this is covered by v6.0.0 which enables or disables both vertical or horizontal repeating
