### ISSUE TITLE
Zoom not working correctly with bounding-box

### ISSUE THREAD

**Issue by Maradox** [osmdroid/osmdroid#762]
When using a bounding-box, and you zoom near the edges of the screen, the scroll after the zoom-animation snaps to a different location (inwards).

Possible reason:
During the calculation of the new scroll-position, the bounding-box at the previous zoom level is used in combination with the scroll-position on the new zoom level. 
This at least would explain the behaviour that the scroll snaps back inwards when near an edge.

**Comment by monsieurtanuki** [comment]
I think other issues are related, including #745 and #761.

The problem is that when we let Mr. Android manipulate a `MapView` during a pinch gesture or an animation, we lose the control over it.
The good news is that we don't really need to control the `MapView` as we can control the `Projection`.

A solution to those issues is then to enforce the limits (zoom min/max, bounding box) _also_ on the `Projection`.
I'll work on the subject and should solve the issues within a week - assuming my hypothesis is right.

**Comment by monsieurtanuki** [comment]
@Maradox I just started working on it, and I believe that `MapView.setPositionAndScale` is where the fix should be done (in first approach). Very similar to what you did in #761. Are you currently working on it or shoud I go on with my dev?

**Comment by Maradox** [comment]
#761 already got merged, and I'm not working on it. Go for it

**Comment by monsieurtanuki** [comment]
I still believe that the bug is in `MapView.setPositionAndScale`, where we should check the limits by calling `checkScrollableAreaBoundingBox`.
This requires to know the "pinched" values of the boundary's four corners. So far I know how to transform `GeoPoint` into `Point`, but I haven't managed to understand the extra pinch gesture point transformation step.
Any help would be appreciated on how to compute the actual pixel coordinates during a pinch gesture.

**Comment by monsieurtanuki** [comment]
I think I nailed it. Finally much easier than I thought - after spending hours on the subject...
Should be able to PR within a week.

**Comment by spyhunter99** [comment]
#282 #334 #459 related issues
