### ISSUE TITLE
Travis build improvements

### ISSUE THREAD

**Issue by monsieurtanuki** [osmdroid/osmdroid#807]
## Issue Type

[v] Bug
[v] Improvement
[v] Build system related
[v] Performance

## Description and/or steps/code to reproduce the problem

In my latest push (#800) I tried about 10 times to re-run the travis build. And it's still not working. That's a very frustrating experience.

Most of the time, it failed because of time limit. As @spyhunter99 mentioned, we shouldn't expect the travis devices to run fast. Fair enough. Therefore what we can do is in the travis build parameters or in the code.

I don't know anything about travis build parameters; I let @spyhunter99 share his views on the subject.

I have some ideas about the code.
In `SampleFactory`, we jumped within last month from 71 to 80 test activities to be run. Is that a bad thing? No. If we don't do anything, are we going to have more test activities? Of course. But if it means we are doomed to systematically exceed the travis time limit, there are things we can do:
* remove deprecated, useless or duplicate test activities
* increase the speed of the test activities (which of course was not at all taken into consideration in the first place, as it was not the point)
* consider that we can accept that we don't need to systematically run all test activities and just focus on the 50 first test activities (with random order)

Occasionally, it failed because a test failed.
If we're not lucky, we end up with a raw log saying something like:
> :OpenStreetMapViewer:connectedDebugAndroidTest
org.osmdroid.test.ExtraSamplesTest > testActivity[test11(AVD) - 2.2] [31mFAILED [0m
Test failed to run to completion. Reason: 'Instrumentation run failed due to 'Process crashed.''. Check device logcat for details
Tests on test11(AVD) - 2.2 failed: Instrumentation run failed due to 'Process crashed.'
:OpenStreetMapViewer:connectedDebugAndroidTest FAILED
FAILURE: Build failed with an exception.
What went wrong:
Execution failed for task ':OpenStreetMapViewer:connectedDebugAndroidTest'.
org/gradle/logging/ConsoleRenderer

What should I fix using that kind of logs? I don't know, it's not verbose enough, and I don't think I have access to the logcat.
* `ExtraSamplesTest` could we edited so that we have a more verbose version, letting us know what went wrong among the 80 test activities.
* I saw in another travis raw log that there was a crash.log file, supposedly verbose, but there seems to be a bug that prevents us from reading it: this bug should be fixed. Following is an edited excerpt of the raw log:
> [31;1mThe command "travis_wait 60 ./gradlew clean install connectedCheck" exited with 1.[0m
travis_fold:start:after_failure.1
[0K$ adb pull /sdcard/osmdroid/crash.log
adb: error: remote object '/sdcard/osmdroid/crash.log' does not exist
[0K$ cat crash.log
cat: crash.log: No such file or directory

I'm not even sure that the problem lies with the test activities.
Well, every suggestion that would help make travis build a smooth experience is welcomed!

By the way, I tried to lower the number of test activities to 60, and my travis build failed again, because of the time limit...

### Version of osmdroid the issue relates to:

6.0.0

**Comment by spyhunter99** [comment]
I'll give you the short version.

- Travis lets each job run for a max of 50 minutes give or take and then declares it dead.
- Travis a VM on not very fast hardware and we are running a AVD within that VM.
- Travis is an x86 environment, however the intel drivers are not installed, which means we have to use the ARM based emulator images, which further compounds the problem

Minor correct, SampleFactory is fragment based, not an activity. See also the BugSampleFactory too.
One of the reasons there's a large number of samples was to have simple isolated examples to solve simple problems. Each test fragment is loaded (i think) 5 times in a row. This was done due to numerous memory leaks that we had. Repeating the same fragment over and over helps to force the issue.

If osmdroid crashes, there will be a crash log file created in the avd. The travis build script will attempt to fetch it and print to stdout. This doesn't always work if the AVD doesn't boot

I rarely have issues with running on my device. I usually set the screen to never sleep while charging during the test. Part of the prerelease check list is run the tests with a high repetition count in ExtraSamplesTest.

There probably a 75% chance of a given build failing for no apparent reason.

I suppose we could drop the connectedCheck parts of the travis build. Using roboelectric may be an option too.

**Comment by spyhunter99** [comment]
Some additional comments, some of the fragments/samples download files off the net, such as map tiles, wms xml files, etc. If there is a connectivity problem or a problem at the other end, or it's running slower than normal, this can also cause test failures

**Comment by monsieurtanuki** [comment]
@spyhunter99 I don't understand that much about the process, but when I have a look at the logs I have the funny impression that all "connectedCheck" tests are run 60 times in a row:
````
travis_wait 60 ./gradlew clean install connectedCheck
Still running (32 of 60): ./gradlew clean install connectedCheck
````
I know that each time `ExtraSamplesTest.executeTest` is run, the execution order of the 80 test fragments is randomized; therefore we can test potentially different behaviors between the runs. But running them 60 times (if it is what it means) is a bit too much, and anyway doesn't fit in the travis window anymore. We could lower that number of iterations.

> Each test fragment is loaded (i think) 5 times in a row. This was done due to numerous memory leaks that we had. Repeating the same fragment over and over helps to force the issue.

I checked in `ExtraSamplesTest.executeTest`, and it looks like each fragment is now run only once, though there obviously used to be several runs:
````java
for (int k = 0; k < 1; k++) {
````
Developers may know that the test fragment they developed is sensitive - repetition and memory leaks wise - and specifically say that it's safer to run the test x times. In some other test fragments that wouldn't make any sense, and only one run would be enough. We could add a method in `BaseSampleFragment`, something like `int getRecommandedNumberOfRuns()` with 1 as default return value, so that each time we run a test fragment's tests, we run the most relevant number of times.

**Comment by spyhunter99** [comment]
travis_wait 60 is the work around for travis canceling a build with no output to std out or std err for more than 10 minutes. This happens when the tests are running on the avd. `60` is wait 60 minutes at max, although travis won't let us run that long anyhow.

concur on the rest.

**Comment by spyhunter99** [comment]
travis unfortunately has been less than useful for running against avds. maybe we should just disable that part. It would obviously fix all of our intermittent build issues

**Comment by monsieurtanuki** [comment]
@spyhunter99 What are the alternate solutions?
1. running less tests - picking which tests are more relevant, or saying that among the random 80 test fragments we run only 50
1. running tests within our own time limit inside `ExtraSamplesTest` - we try to run the 80 test fragments as long as we don't go beyond a duration of 25 minutes
1. when applicable, transforming some `connectedCheck` tests with a more standard JUnit test - would that help?
1. using another tool than travis - roboelectric as you mentioned?
1. removing altogether the `connectedCheck` tests - would that mean that those tests will no longer be part of the build at all?

Btw only 7 fragments override `runTestProcedures`, and only 4 implement `skipOnCiTests` as `true`.
Would it make sense to consider that only fragments with actual implementation of `runTestProcedures` deserve to be run by the `connectedCheck` process?

**Comment by spyhunter99** [comment]
1. Yes this would help. They are randomized in order to force issues
2. I think may of the test fragments can be skipped to reduce the build time
3. This would definitely help
4. Using travis is still the way to go, but skipping the android virtual device in favor of something else, such as roboelectric would probably solve our problems. Unfortunately it's not quite the same as running on a real device
5. an option but this is not ideal

**Comment by monsieurtanuki** [comment]
The fastest solution that makes sense functionnally is to implement `skipOnCiTests` as `true` by default, and override it as `false` only for test fragments that override `runTestProcedures`.
@spyhunter99 Ok with that?

**Comment by spyhunter99** [comment]
ok

**Comment by monsieurtanuki** [comment]
@spyhunter99 I guess we can close it now.
