### ISSUE TITLE
regression in performance of Polyline

### ISSUE THREAD

**Issue by shiroyagi** [osmdroid/osmdroid#834]
## Issue Type

[ ] Question
[*] Bug
[ ] Improvement
[ ] Build system related
[ ] Performance
[ ] Documentation

## Description and/or steps/code to reproduce the problem

With hardware acceleration on and drawing a Polyline containing 3 points whose extent is several times the size of the map viewport, panning performance is significantly reduced in 6.0.0 compared to 5.6.6 (see attached screenshots from GPU profiler) and sometimes stutters.  I suspect the cause is the change from canvas.drawLines() to drawPath() in #725.  drawLines() was found to give much better performance in #353.  Since Path is needed for Polygon, maybe this unfortunately means they shouldn't share code?

### Version of osmdroid the issue relates to: 6.0

**5.6.6 profile output below**
![osmdroid566](https://user-images.githubusercontent.com/8389325/34417113-a0d404b8-ebee-11e7-9155-39434ccdb5e7.png)

**6.0.0 profile output below**
![osmdroid600](https://user-images.githubusercontent.com/8389325/34417115-a57df320-ebee-11e7-84f6-a4a0f3cda8ef.png)

**Comment by monsieurtanuki** [comment]
I don't mind switching `Polyline` back to `drawLines()` for performance reasons.
Does anything come to mind as why it could be a bad idea to do so - something like "oh, with `Path` we can do that and we cannot with `drawLines()`?

**Comment by shiroyagi** [comment]
Not to me.  Path has many more capabilities (which likely reduces the potential for GPU optimisation) but we are not using them in this case.  Do you know what the issue with Polyline disappearing at zoom>=25 mentioned on #725 was and how it is resolved with the current code (clipping)?

**Comment by monsieurtanuki** [comment]
>  Do you know what the issue with Polyline disappearing at zoom>=25 mentioned on #725 was and how it is resolved with the current code (clipping)?

That goes beyond this issue, but basically the hardware acceleration does not support `canvas.scale` operations (according to Android docs) and as we used this method to display maps (we don't anymore cf. #790) the side effect was that the Path didn't appear when the pixel coordinates went "too big" (I cannot be more explicit because it's a combination of "not supported" x "side effect" x "no explicit limit given by Android docs").
The fix was to clip `Path` coordinates into a square whose dimension is approximately `Math.max(screenWidth, screenHeight)` (cf. `SegmentClipper`).
So far we populate a `Path` with those clipped coordinates, but there's no reason why we couldn't have a different behavior between `Polyline` and `Polygon`. I'm actually working on the subject - well, not really, but I'm deeply into the "polyline with arrows" enhancement (#809) and that would be easy (and fast) for me to fix that within at most a couple of days.

**Comment by shiroyagi** [comment]
Ok, sounds good.  I was wondering if it would be possible to reuse LinearRing and SegmentClipper by refactoring the first to work on a point list internally and only convert to Path on output if required?

**Comment by monsieurtanuki** [comment]
Oh sure, actually now I have a dedicated class called `PathBuilder` that only `moveTo` the first point and `lineTo` the next points in order to build the `Path`. I just have to create a similar class with `drawLine` as target.

**Comment by shiroyagi** [comment]
Great.  I wonder what the overhead of clipping a large number of points is.  Perhaps if it clipped to `3*Math.max(screenWidth, screenHeight)` it could avoid a lot of re-clipping when panning?  I could have a look at profiling to find out when you have finished.

**Comment by monsieurtanuki** [comment]
@shiroyagi I just switched the `Polyline` back to `Canvas.drawLine`, but there's a little problem: there's no continuity between the lines - you can see line breaks, especially on curves:
![device-2017-12-29-110331](https://user-images.githubusercontent.com/11576431/34434891-a9ef0a0c-ec89-11e7-8b37-9defd51b74c6.png)
And this doesn't happen when using `Path`, where segment transitions are smooth.
Is there a trick so that we can avoid to use `Path` but still enjoy continuous segments?

**Comment by monsieurtanuki** [comment]
@shiroyagi I'm still a bit surprised by your slow panning for only 2 segments.
Is there something special you do in your app - more specifically, do you happen to use some of the [hardware acceleration unsupported drawing operations](https://developer.android.com/guide/topics/graphics/hardware-accel.html#unsupported)?

**Comment by shiroyagi** [comment]
I am only using a line width of 3.0 so I doubt the breaks would be visible.  Have you tried a similar width with 5.6.6, it sounds like it may have been an existing issue?  A possible solution would be to extend each segment length by a fraction of the line width so they overlap.

No nothing special, just a straightforward use of Polyline.  Is it possible the Path is rendered and passed to the GPU as a bitmap so it is the area that is significant (not the number of segments) and this may be much greater than that of the viewport?  The profiling shows performance deteriorates the more you zoom in.  Lines are basic GL primitives and can be defined more efficiently.  The above profiling was with just 3 points, and panning is noticeably less smooth in this case.  However I first noticed a problem with 5k points which may also suffer from other delays (eg. clipping calculation?), and in this case the the profiler shows much more blue indicating additional time in onDraw().

**Comment by monsieurtanuki** [comment]
There are things to optimize in the clipping process. For instance we constantly create new objects (for a List of PointL) in the UI thread (onDraw): this can be fixed by implementing a dedicated optimized ListPointL class.

For the segment breaks, a fix could be to draw at each vertex a circle with the radius half the line width. Should be ok as long as there's no alpha involved.

I don't understand how it could be slower with a higher zoom. The idea is precisely to clip the segments _before_ adding them to the Path, and in a small clip area. Therefore the Path area is always small, and doesn't even know how big it was supposed to be without the clip operation. But I think the invisible clipped parts deserve to be cleaned. How could it be a problem with only 3 points and 2 segments - I don't know.

I guess this issue can be split in several parts:
1. optimizing the clipping process in time and memory
2. double-checking that Path is definitely much slower than drawLine, regardless of the clipping aspects
3. implementing a good-looking version of drawLine, segmentbreakwise
4. possibly implement a distinct solution for Polyline without clipping, assuming there's no problem with hardware acceleration vs. drawLine

**Comment by shiroyagi** [comment]
> I don't understand how it could be slower with a higher zoom.
Me neither, but that's what I saw.

Using a larger clip region (1) and only using the good-looking version (3) for thick lines would seem like a good idea.

**Comment by monsieurtanuki** [comment]
Solved in #838
