### ISSUE TITLE
Scroll on edges not working correctly with repetition mode disabled and boundingBox enabled

### ISSUE THREAD

**Issue by Maradox** [osmdroid/osmdroid#843]
When the map is scrolled to an edge, it is hard to scroll away from that edge.

**Reproduce**

In order to reproduce:
* Open Sample `TileProviders/Assets Only with Repetition Modes`
* Disabled `Horizontal` and `Vertical`
* Enable `Limit Bounds`
* Zoom far into the map (so the screen size is less than the map size)
* Scroll to an edge and scroll a few times further
* *Problem:* Scroll away from the edge. The scroll does not work until the finger is moved really far or you scroll several times.

**Related code**

The related code is located in `adjustOffsets()` and `checkScrollableOffset()` in the `Projection` class. The problem is that when creating a new Projection, `mOffsetX` and `mOffsetY` are newly calculated and still far beyond the edge (because `pScrollX` and `pScrollY` themselves are not limited by bounds, and the offsets use these values for their initialization). Thus, when scrolling to the edge and further, the projection class restores the offset from beyond the edge. In order to scroll inwards from the edge, one has to first go from the offset to 0, until the actual scroll happens.

So the issue is ultimately caused by `pScrollX` and `pScrollY` which represent values than can go beyond the edge, but are used for calculating the offsets when creating the projection. I'm not sure however how to fix this problem.

6.0.0-SNAPSHOT

**Comment by monsieurtanuki** [comment]
I reproduced the bug.
I think the problem is something like that: when we adjust the offsets in `Projection`, we should somehow impact back the `MapView` scroll values.
In the case of this issue, the `MapView` scroll values keep growing when you scroll beyond the limit, and the `Projection` scroll values are adjusted accordingly (`MapView` doesn't know that). When you scroll back, the `MapView` scroll values are still beyond the limit (less and less, though) and `Projection` scroll values are still adjusted: the map doesn't move until the `MapView` scroll values go below the limit.

A remark slightly related to this issue: wouldn't it make sense to handle the horizontal replication differently? Like for instance being able to center the map on every longitude on zoom 0 with horizontal and vertical unchecked, and limit bounds checked?

**Comment by monsieurtanuki** [comment]
Now that I'm thinking again about it, it used to be working OK. When I worked specifically on the scroll limit area feature (#742), I tested that, and if you go to the "New York Central Park" "Limited scroll area" demo, now it's not working anymore - same bad behavior as the current issue.
