### ISSUE TITLE
Map.getCenter vs Map.getMapCenter return two different values

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#868]
## Issue Type

[ ] Question
[x ] Bug
[x] Improvement
[ ] Build system related
[ ] Performance
[x] Documentation

## Description and/or steps/code to reproduce the problem

not sure what the difference is between these two but they return different values and it's no javadocs for them.

### Version of osmdroid the issue relates to:

6.0.0/head

**Comment by monsieurtanuki** [comment]
* `MapView.getCenter` gives to the `Projection` the _desired_ map center, typically set by `MapView.setCenter` when you want to center a map on a particular point. It's its only purpose. It relies on member `mCenter`.
* `MapView.getMapCenter` gives you the actual current map center, as the `Projection` computes it from the middle of the screen. Most of the time it's supposed to be _approximately_ the same value (because of computing rounding side effects), but in some cases (current zoom gesture or scroll limits) the values may differ (typically, when `Projection.adjustOffsets` had to fine-tune the map center).

I agree, it's a source of confusion. Due to the fact that we use `MapView.getProjection()` with no parameters - that's why we need to store temporarily the map center for the next `Projection`.

My suggestions:
* renaming `setCenter` to `setExpectedCenter`
* renaming `getCenter` to `getExpectedCenter`, and lowering its access to package-private

@spyhunter99 Do you agree with that suggestion?

**Comment by spyhunter99** [comment]
so `getCenter` is only applicable when map repetition is on, right?

**Comment by monsieurtanuki** [comment]
I'd say that `MapView.getCenter` should _never_ be used _except_ by the constructor of `Projection`. It's just a deferred setting of the expected next map center computed by the `Projection`'s constructor, with no guarantee it will be 100% respected.

I don't think it can be related to map repetition, but I'm not an expert in map repetition. What would happen if you use `MapView.setCenter` with a longitude lower than -180 or greater than 180, I don't know.

**Comment by spyhunter99** [comment]
gotcha, make it protected then and add some javadocs explain this, why it's there and what its used for, maybe reference this issue.

**Comment by spyhunter99** [comment]
@monsieurtanuki working on the changes now. any idea when the get/setCenter was added (specifically what issue it was part of)? I just want to link the issues together

**Comment by monsieurtanuki** [comment]
@spyhunter99 Oh, I was currently doing this as it looked like a quick win.
As I was doing that I was wondering if it was relevant to rename `setCenter` to `setExpectedCenter` as it would impact existing code. And I myself renamed `mCenter` as `mExpectedCenter`. Well, not a big deal anyway.

About the get/setCenter, I think it was part of #681 in the "store and restore the actual map center (instead of scroll) and the map orientation" step

> Why should we use the map center instead of the scroll? Because when tilting the smartphone portrait-landscape-wise, the map center is kept only modulo the difference between `MapView`'s width and height.
