### ISSUE TITLE
Coordinate conversion accuracy

### ISSUE THREAD

**Issue by Maradox** [osmdroid/osmdroid#929]
I found that the conversions do not work completely accurately.

Example:
1. Pixel = (328, 954)
2. `Projection.fromPixels()` = (-70.64506180813729,-83.73913043478261)
3. `Projection.toPixels()` = (326, 952) => it shifted by 2px horizontally and vertically

The same holds true when converting from GeoPoint->Projected->Pixels.

### Version of osmdroid the issue relates to:

6.0.0-Snapshot

**Comment by monsieurtanuki** [comment]
@Maradox Here are the following reasons why we may have computation inaccuracy:
1. `int` rounding side effects
1. `double` precision limits
1. `Math` methods accuracy limits (`pow`, `cos`, `sin`, `atan`, `PI`, `log`, `exp`)
1. and of course, bugs ;)

That being said, longitude/x conversions shouldn't be impacted at all by the more fragile part (`Math`).
Could you provide the whole input parameters of the `Projection` constructor in your example?

**Comment by Maradox** [comment]
I created a test-case for it (only for fromPixels / toPixels though): https://github.com/Maradox/osmdroid/tree/bug/%23929

I tested several parameters and it doesn't seem to matter - the conversion always creates an offset of 2px.

Branch: `bug/#929`
TestClass: `org.osmdroid.views.ProjectionTest`

**Comment by monsieurtanuki** [comment]
@Maradox Actually there's already a unit test class (`org.osmdroid.util.ProjectionTest`): yes, it's not where it should be.

I ran some additional tests on `testCenteredGeoPoint` ("If both Projection's scrolls are 0, the geo center is projected to the screen rect center") and it looks like `Projection.toPixels` works very well: we could even remove the `delta=2d` parameter in order to expect strict equality.

The test you implemented is more or less what is in `testPixelToGeoToPixel`. As I'm rather confident in `Projection.toPixels` (cf. `testCenteredGeoPoint`), I guess the problems lies in `Projection.fromPixels`.
So far I haven't seen anything explicitly wrong in the code. My educated guess is that we can't expect to have a perfect bijection between 512 pixels (zoom level = 1) and an infinity of longitude values between -180 and 180, especially given the inaccuracies inherent to Math in Java already mentioned in a previous comment.
I'll have another look at it, and possibly implement other unit test methods.

**Comment by monsieurtanuki** [comment]
I may have found something fishy, in `TileSystem.ClipToLong`.
This method is used to convert a `double` value into a `long` while ensuring that the result fits into `[0, max[` values.
The typical use case is converting a temporary `double` `[0, mapSize]` value into a `long` `[0, mapSize-1]` mercator value.
How do we evenly distribute values _without side effects_? A simple `Math.round(myDoubleValue / (max - 1))`? Still investigating...

**Comment by monsieurtanuki** [comment]
Fixed by #948 
@Maradox Now your test unit passes. Please reopen this issue and/or enrich the unit tests if needed.
