### ISSUE TITLE
Re: recent refactor of polyline and polygon

### ISSUE THREAD

**Issue by spyhunter99** [osmdroid/osmdroid#968]
## Issue Type

[ ] Potential issue

### Potential issue 1, removal of addPoint

It's been brought up before that at least one user is extended Polyline in order use the protected method `addPoint`. Recent commit by @MKergall removed that method in commit c70ef01. 

### Potential issue 2, removal of the id field from Polygon and Polyline

The same commit also removed the field `id` from Polygon and Polyline along with their getters and setters. This was a user request from OsmbonusPack that was needed for parsing some kind of identifier from KML. This was referenced here: https://github.com/MKergall/osmbonuspack/issues/306. 

### Fix it plan

We'll probably ok with the removal of appPoint but i think the removal of the id field with the betters and setters will probably break the build on bonus pack...

**Comment by MKergall** [comment]
Issue 1: 
addPoint doesn't exist in Google Maps API. It was not properly implemented (geodesic option for instance). 
This is doing the job (not very efficiently): 

`polyline.setPoints(polyline.getPoints().add(myPoint));`

If there is a need, I can implement it (properly and efficiently). 

Issue 2: don't worry, id is still available, with setters and getters. It has been moved in parent class, OverlayWithIW, so that all those child classes inherit from this common code, instead of duplicating.

**Comment by spyhunter99** [comment]
ok then. no further action needed. i will tag this issue as being fixed in 6.0.2 for documentation purposes

**Comment by shiroyagi** [comment]
I was using addPoint() too.
1. it was convenient to be able to extend the line without having re-set all points
2. I don't store my points in List<GeoPoint> so setPoints() requires an additional temporary copy
3. the current  code doesn't seem well optimised for large polylines: there are multiple copies in LinearRing and Polyline in addition to the argument to setPoints()

I would like to get rid of Polyline.mOriginalPoints.  The client can retain a copy if it needs it rather than calling getPoints().  Only a single point need be kept for setDefaultInfoWindowLocation().

As a future optimisation for large lines, consider ArrayList<Double> instead of ArrayList<GeoPoint> internally and ideally provide a Polyline.setPoints(ArrayList<Double> lat, ArrayList<Double> lng) interface.  Is their performance significantly different on Android?

**Comment by MKergall** [comment]
@shiroyagi 

1) I agree, and I just pushed a commit adding addPoint API to Polygon and Polyline. 

3) I also would prefer to get rid of these mOriginalPoints, which are here just to provide getPoints method. If we remove mOriginalPoints, we should remove getPoints method (which is available in Google API). 
Personnaly, I don't care (in MVC words, I handle my Model on my side, I don't get it from the View), but I think we need a feedback from other users before. 

N.B. Effectively, using double[size][3] was much much more efficient when creating of large polylines (no object creation). This has been lost following changes around perfs/wrapping/arrows and introduction of LinearRing. And it's not compatible with addPoint...

**Comment by shiroyagi** [comment]
(1) great, thanks

(3) I guess it would be possible to add an `enableGetPoints(boolean)` and not populate `mOriginalPoints` when disabled, or is that a bit too messy?

Perhaps some kind of interface:
```
public interface IPointList {
  int getSize();
  double getLatitude(int i);
  double getLongitude(int i);
  boolean isMutable();
  ...
}

Polyline.setPoints(IPointList points) {}
```
You could then use whatever storage was most convenient, and potentially have an immutable Polyline instance optimised for large lines, and another less efficient but mutable one.

ps. it would be nice if breaking API changes could be restricted to major version number changes

**Comment by shiroyagi** [comment]
`clearPath()` has also been removed, but I suppose you can just `setPoints()` with an empty list.

However `addPoint()` doesn't seem to work as before.  If I populate a `PolyLine` purely using `addPoint()`, nothing is drawn.
