### ISSUE TITLE
naked /** @deprecated */ for toPixelsFromProjected

### ISSUE THREAD

**Issue by pasniak** [osmdroid/osmdroid#992]
```
    /** @deprecated */
    @Deprecated
    public Point toPixelsFromProjected(PointL in, Point reuse) {
```
in https://github.com/osmdroid/osmdroid/blob/0aaa8dc31f9f8adae022910a7df1d55ca78efbaf/osmdroid-android/src/main/java/org/osmdroid/views/Projection.java#L265

It's not clear what to replace it with...

## Issue Type

[x] Documentation

6.0.2-SNAPSHOT

**Comment by monsieurtanuki** [comment]
@pasniak Satisfied by #995?

**Comment by pasniak** [comment]
```
	/**
     * @since 6.0.0
     */
    public PointL getLongPixelsFromProjected(final PointL in, final double powerDifference, final boolean pCloser, final PointL reuse) {

```

The call to `getLongPixelsFromProjected` looks quite cryptic to me :) Maybe the names (in, powerDifference, pCloser, reuse) could be less cryptic?

I understand mMapCoordsTranslated is the result.  It's a bit like C++ optimization i.e passing the ref :)  if that is the case why do we return it (when it is suboptimal)?

**Comment by monsieurtanuki** [comment]
They look cryptic to me too :)
But even the concept of "projected" is a bit cryptic; in a better world we wouldn't need that. It's only used when we have tons of `GeoPoint`s to frequently project on a screen: instead of systematically call the heavy `Math` projection functions, we project once on a "projected" virtual screen with a "big" tile size, and then we just have to reduce into the actual smaller projection virtual screen.

I believe the names could be slightly less cryptic, but not that much; I'd rather say we need more comments instead.

`Projection` is a sort of work in progress, there are `TODO` tags and recent new concepts and optimization around map replication and `Polygon` drawing.

About the `reuse` + `return` part of your comment, I just "reused" (!) the method parameter pattern in `Projection`. I'm not against not returning a value: how suboptimal is the unnecessary "return" part?

**Comment by monsieurtanuki** [comment]
Well, we have to deal with a code with a long history and many contributors...

**Comment by monsieurtanuki** [comment]
@pasniak Just PR'ed #1088.

**Comment by monsieurtanuki** [comment]
@pasniak ping

**Comment by monsieurtanuki** [comment]
I assume it's decent now. Feel free to reopen if necessary.
